# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'binary_data_form.ui'
#
# Created: Mon Aug 31 09:18:17 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_BinaryDataForm(object):
    def setupUi(self, BinaryDataForm):
        BinaryDataForm.setObjectName("BinaryDataForm")
        BinaryDataForm.setWindowModality(QtCore.Qt.ApplicationModal)
        BinaryDataForm.resize(385, 345)
        BinaryDataForm.setMinimumSize(QtCore.QSize(385, 345))
        BinaryDataForm.setMaximumSize(QtCore.QSize(385, 345))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        BinaryDataForm.setFont(font)
        BinaryDataForm.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.formLayout = QtGui.QFormLayout(BinaryDataForm)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(BinaryDataForm)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.author_txt_box = QtGui.QTextEdit(BinaryDataForm)
        self.author_txt_box.setMinimumSize(QtCore.QSize(218, 21))
        self.author_txt_box.setMaximumSize(QtCore.QSize(218, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.author_txt_box.setFont(font)
        self.author_txt_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.author_txt_box.setObjectName("author_txt_box")
        self.horizontalLayout.addWidget(self.author_txt_box)
        self.label_2 = QtGui.QLabel(BinaryDataForm)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.year_txt_box = QtGui.QTextEdit(BinaryDataForm)
        self.year_txt_box.setMinimumSize(QtCore.QSize(55, 21))
        self.year_txt_box.setMaximumSize(QtCore.QSize(55, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.year_txt_box.setFont(font)
        self.year_txt_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.year_txt_box.setObjectName("year_txt_box")
        self.horizontalLayout.addWidget(self.year_txt_box)
        self.formLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtGui.QLabel(BinaryDataForm)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(BinaryDataForm)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 2, 1, 1)
        self.label_10 = QtGui.QLabel(BinaryDataForm)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setWeight(75)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 3, 1, 1)
        self.label_3 = QtGui.QLabel(BinaryDataForm)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.raw_data_table = QtGui.QTableWidget(BinaryDataForm)
        self.raw_data_table.setMinimumSize(QtCore.QSize(305, 89))
        self.raw_data_table.setMaximumSize(QtCore.QSize(305, 89))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.raw_data_table.setFont(font)
        self.raw_data_table.setFrameShadow(QtGui.QFrame.Plain)
        self.raw_data_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.raw_data_table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.raw_data_table.setProperty("showDropIndicator", QtCore.QVariant(True))
        self.raw_data_table.setAlternatingRowColors(True)
        self.raw_data_table.setShowGrid(True)
        self.raw_data_table.setGridStyle(QtCore.Qt.DashDotLine)
        self.raw_data_table.setRowCount(3)
        self.raw_data_table.setColumnCount(3)
        self.raw_data_table.setObjectName("raw_data_table")
        self.raw_data_table.setColumnCount(3)
        self.raw_data_table.setRowCount(3)
        self.gridLayout.addWidget(self.raw_data_table, 1, 1, 3, 3)
        self.label_4 = QtGui.QLabel(BinaryDataForm)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_9 = QtGui.QLabel(BinaryDataForm)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setWeight(75)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 3, 0, 1, 1)
        self.formLayout.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtGui.QSpacerItem(188, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_7 = QtGui.QLabel(BinaryDataForm)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.chi_txt_box = QtGui.QTextEdit(BinaryDataForm)
        self.chi_txt_box.setMinimumSize(QtCore.QSize(40, 19))
        self.chi_txt_box.setMaximumSize(QtCore.QSize(40, 19))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.chi_txt_box.setFont(font)
        self.chi_txt_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.chi_txt_box.setObjectName("chi_txt_box")
        self.horizontalLayout_2.addWidget(self.chi_txt_box)
        self.label_8 = QtGui.QLabel(BinaryDataForm)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.chi_p_txt_box = QtGui.QTextEdit(BinaryDataForm)
        self.chi_p_txt_box.setMinimumSize(QtCore.QSize(40, 19))
        self.chi_p_txt_box.setMaximumSize(QtCore.QSize(40, 19))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.chi_p_txt_box.setFont(font)
        self.chi_p_txt_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.chi_p_txt_box.setObjectName("chi_p_txt_box")
        self.horizontalLayout_2.addWidget(self.chi_p_txt_box)
        self.formLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout.addItem(spacerItem1, 3, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_11 = QtGui.QLabel(BinaryDataForm)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.effect_cbo_box = QtGui.QComboBox(BinaryDataForm)
        self.effect_cbo_box.setMinimumSize(QtCore.QSize(76, 20))
        self.effect_cbo_box.setMaximumSize(QtCore.QSize(76, 20))
        self.effect_cbo_box.setObjectName("effect_cbo_box")
        self.horizontalLayout_3.addWidget(self.effect_cbo_box)
        self.formLayout.addLayout(self.horizontalLayout_3, 4, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(BinaryDataForm)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.buttonBox)
        self.effect_grp_box = QtGui.QGroupBox(BinaryDataForm)
        self.effect_grp_box.setMinimumSize(QtCore.QSize(360, 41))
        self.effect_grp_box.setMaximumSize(QtCore.QSize(411, 41))
        self.effect_grp_box.setObjectName("effect_grp_box")
        self.widget = QtGui.QWidget(self.effect_grp_box)
        self.widget.setGeometry(QtCore.QRect(0, 10, 361, 21))
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setSpacing(2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_12 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_4.addWidget(self.label_12)
        self.effect_txt_box = QtGui.QTextEdit(self.widget)
        self.effect_txt_box.setMinimumSize(QtCore.QSize(45, 19))
        self.effect_txt_box.setMaximumSize(QtCore.QSize(45, 19))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.effect_txt_box.setFont(font)
        self.effect_txt_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.effect_txt_box.setObjectName("effect_txt_box")
        self.horizontalLayout_4.addWidget(self.effect_txt_box)
        self.label_13 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_4.addWidget(self.label_13)
        self.low_txt_box = QtGui.QTextEdit(self.widget)
        self.low_txt_box.setMinimumSize(QtCore.QSize(45, 19))
        self.low_txt_box.setMaximumSize(QtCore.QSize(45, 19))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.low_txt_box.setFont(font)
        self.low_txt_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.low_txt_box.setObjectName("low_txt_box")
        self.horizontalLayout_4.addWidget(self.low_txt_box)
        self.label_14 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_4.addWidget(self.label_14)
        self.high_txt_box = QtGui.QTextEdit(self.widget)
        self.high_txt_box.setMinimumSize(QtCore.QSize(45, 19))
        self.high_txt_box.setMaximumSize(QtCore.QSize(45, 19))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.high_txt_box.setFont(font)
        self.high_txt_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.high_txt_box.setObjectName("high_txt_box")
        self.horizontalLayout_4.addWidget(self.high_txt_box)
        self.label_15 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_4.addWidget(self.label_15)
        self.effect_p_txt_box = QtGui.QTextEdit(self.widget)
        self.effect_p_txt_box.setMinimumSize(QtCore.QSize(45, 19))
        self.effect_p_txt_box.setMaximumSize(QtCore.QSize(45, 19))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.effect_p_txt_box.setFont(font)
        self.effect_p_txt_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.effect_p_txt_box.setObjectName("effect_p_txt_box")
        self.horizontalLayout_4.addWidget(self.effect_p_txt_box)
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.effect_grp_box)

        self.retranslateUi(BinaryDataForm)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), BinaryDataForm.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), BinaryDataForm.reject)
        QtCore.QMetaObject.connectSlotsByName(BinaryDataForm)

    def retranslateUi(self, BinaryDataForm):
        BinaryDataForm.setWindowTitle(QtGui.QApplication.translate("BinaryDataForm", "Enter Binary Data", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("BinaryDataForm", "author", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("BinaryDataForm", "year", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("BinaryDataForm", "event", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("BinaryDataForm", "no event", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("BinaryDataForm", "total", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("BinaryDataForm", "group 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("BinaryDataForm", "group 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("BinaryDataForm", "total", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("BinaryDataForm", "χ²", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("BinaryDataForm", " χ² p-val", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("BinaryDataForm", "effect", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("BinaryDataForm", "est.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("BinaryDataForm", "low", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("BinaryDataForm", "high", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("BinaryDataForm", "p-val", None, QtGui.QApplication.UnicodeUTF8))

