# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'binary_data_form2.ui'
#
# Created: Fri Apr 12 14:30:02 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_BinaryDataForm(object):
    def setupUi(self, BinaryDataForm):
        BinaryDataForm.setObjectName(_fromUtf8("BinaryDataForm"))
        BinaryDataForm.resize(394, 419)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/misc/meta.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        BinaryDataForm.setWindowIcon(icon)
        self.verticalLayout_4 = QtGui.QVBoxLayout(BinaryDataForm)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setContentsMargins(-1, -1, -1, 9)
        self.gridLayout_5.setVerticalSpacing(4)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.event_lbl_3 = QtGui.QLabel(BinaryDataForm)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.event_lbl_3.setFont(font)
        self.event_lbl_3.setAlignment(QtCore.Qt.AlignCenter)
        self.event_lbl_3.setObjectName(_fromUtf8("event_lbl_3"))
        self.gridLayout_5.addWidget(self.event_lbl_3, 0, 1, 1, 1)
        self.label_18 = QtGui.QLabel(BinaryDataForm)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_5.addWidget(self.label_18, 0, 2, 1, 1)
        self.label_19 = QtGui.QLabel(BinaryDataForm)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_5.addWidget(self.label_19, 0, 3, 1, 1)
        self.label_20 = QtGui.QLabel(BinaryDataForm)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_5.addWidget(self.label_20, 1, 0, 1, 1)
        self.raw_data_table_3 = QtGui.QTableWidget(BinaryDataForm)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.raw_data_table_3.sizePolicy().hasHeightForWidth())
        self.raw_data_table_3.setSizePolicy(sizePolicy)
        self.raw_data_table_3.setMinimumSize(QtCore.QSize(305, 93))
        self.raw_data_table_3.setMaximumSize(QtCore.QSize(305, 84))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.raw_data_table_3.setFont(font)
        self.raw_data_table_3.setFrameShadow(QtGui.QFrame.Plain)
        self.raw_data_table_3.setLineWidth(1)
        self.raw_data_table_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.raw_data_table_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.raw_data_table_3.setProperty("showDropIndicator", True)
        self.raw_data_table_3.setAlternatingRowColors(True)
        self.raw_data_table_3.setShowGrid(True)
        self.raw_data_table_3.setGridStyle(QtCore.Qt.DashDotLine)
        self.raw_data_table_3.setRowCount(3)
        self.raw_data_table_3.setColumnCount(3)
        self.raw_data_table_3.setObjectName(_fromUtf8("raw_data_table_3"))
        self.raw_data_table_3.horizontalHeader().setVisible(False)
        self.raw_data_table_3.horizontalHeader().setHighlightSections(False)
        self.raw_data_table_3.verticalHeader().setVisible(False)
        self.gridLayout_5.addWidget(self.raw_data_table_3, 1, 1, 3, 3)
        self.label_21 = QtGui.QLabel(BinaryDataForm)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_5.addWidget(self.label_21, 2, 0, 1, 1)
        self.label_22 = QtGui.QLabel(BinaryDataForm)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_5.addWidget(self.label_22, 3, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_5)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.clear_Btn_3 = QtGui.QPushButton(BinaryDataForm)
        self.clear_Btn_3.setObjectName(_fromUtf8("clear_Btn_3"))
        self.horizontalLayout_17.addWidget(self.clear_Btn_3)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem)
        self.back_calc_btn_3 = QtGui.QPushButton(BinaryDataForm)
        self.back_calc_btn_3.setEnabled(False)
        self.back_calc_btn_3.setObjectName(_fromUtf8("back_calc_btn_3"))
        self.horizontalLayout_17.addWidget(self.back_calc_btn_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(4)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_17 = QtGui.QLabel(BinaryDataForm)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_13.addWidget(self.label_17)
        self.effect_cbo_box_3 = QtGui.QComboBox(BinaryDataForm)
        self.effect_cbo_box_3.setMinimumSize(QtCore.QSize(76, 20))
        self.effect_cbo_box_3.setMaximumSize(QtCore.QSize(76, 20))
        self.effect_cbo_box_3.setObjectName(_fromUtf8("effect_cbo_box_3"))
        self.horizontalLayout_13.addWidget(self.effect_cbo_box_3)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.groupBox = QtGui.QGroupBox(BinaryDataForm)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        spacerItem2 = QtGui.QSpacerItem(32, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem2, 0, 0, 2, 1)
        self.ci_label_3 = QtGui.QLabel(self.groupBox)
        self.ci_label_3.setText(_fromUtf8(""))
        self.ci_label_3.setObjectName(_fromUtf8("ci_label_3"))
        self.gridLayout_6.addWidget(self.ci_label_3, 0, 2, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(32, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem3, 0, 3, 2, 1)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.est_lbl_3 = QtGui.QLabel(self.groupBox)
        self.est_lbl_3.setMinimumSize(QtCore.QSize(0, 20))
        self.est_lbl_3.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.est_lbl_3.setFont(font)
        self.est_lbl_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.est_lbl_3.setObjectName(_fromUtf8("est_lbl_3"))
        self.horizontalLayout_15.addWidget(self.est_lbl_3)
        self.effect_txt_box_3 = QtGui.QLineEdit(self.groupBox)
        self.effect_txt_box_3.setMinimumSize(QtCore.QSize(50, 20))
        self.effect_txt_box_3.setMaximumSize(QtCore.QSize(50, 20))
        self.effect_txt_box_3.setObjectName(_fromUtf8("effect_txt_box_3"))
        self.horizontalLayout_15.addWidget(self.effect_txt_box_3)
        self.gridLayout_6.addLayout(self.horizontalLayout_15, 1, 1, 1, 1)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.low_lbl_3 = QtGui.QLabel(self.groupBox)
        self.low_lbl_3.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.low_lbl_3.setFont(font)
        self.low_lbl_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.low_lbl_3.setObjectName(_fromUtf8("low_lbl_3"))
        self.horizontalLayout_16.addWidget(self.low_lbl_3)
        self.low_txt_box_3 = QtGui.QLineEdit(self.groupBox)
        self.low_txt_box_3.setMinimumSize(QtCore.QSize(50, 20))
        self.low_txt_box_3.setMaximumSize(QtCore.QSize(50, 20))
        self.low_txt_box_3.setObjectName(_fromUtf8("low_txt_box_3"))
        self.horizontalLayout_16.addWidget(self.low_txt_box_3)
        self.label_23 = QtGui.QLabel(self.groupBox)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_16.addWidget(self.label_23)
        self.high_txt_box_3 = QtGui.QLineEdit(self.groupBox)
        self.high_txt_box_3.setMinimumSize(QtCore.QSize(50, 20))
        self.high_txt_box_3.setMaximumSize(QtCore.QSize(50, 20))
        self.high_txt_box_3.setObjectName(_fromUtf8("high_txt_box_3"))
        self.horizontalLayout_16.addWidget(self.high_txt_box_3)
        self.high_lbl_3 = QtGui.QLabel(self.groupBox)
        self.high_lbl_3.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.high_lbl_3.setFont(font)
        self.high_lbl_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.high_lbl_3.setObjectName(_fromUtf8("high_lbl_3"))
        self.horizontalLayout_16.addWidget(self.high_lbl_3)
        self.gridLayout_6.addLayout(self.horizontalLayout_16, 1, 2, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.line = QtGui.QFrame(BinaryDataForm)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_4.addWidget(self.line)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_24 = QtGui.QLabel(BinaryDataForm)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_18.addWidget(self.label_24)
        self.CI_spinbox_3 = QtGui.QDoubleSpinBox(BinaryDataForm)
        self.CI_spinbox_3.setDecimals(1)
        self.CI_spinbox_3.setMinimum(40.0)
        self.CI_spinbox_3.setMaximum(100.0)
        self.CI_spinbox_3.setSingleStep(0.1)
        self.CI_spinbox_3.setProperty("value", 95.0)
        self.CI_spinbox_3.setObjectName(_fromUtf8("CI_spinbox_3"))
        self.horizontalLayout_18.addWidget(self.CI_spinbox_3)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.inconsistencyLabel_3 = QtGui.QLabel(BinaryDataForm)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.inconsistencyLabel_3.setFont(font)
        self.inconsistencyLabel_3.setObjectName(_fromUtf8("inconsistencyLabel_3"))
        self.horizontalLayout_14.addWidget(self.inconsistencyLabel_3)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem5)
        self.buttonBox_3 = QtGui.QDialogButtonBox(BinaryDataForm)
        self.buttonBox_3.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox_3.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox_3.setObjectName(_fromUtf8("buttonBox_3"))
        self.horizontalLayout_14.addWidget(self.buttonBox_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_14)

        self.retranslateUi(BinaryDataForm)
        QtCore.QObject.connect(self.buttonBox_3, QtCore.SIGNAL(_fromUtf8("rejected()")), BinaryDataForm.reject)
        QtCore.QObject.connect(self.buttonBox_3, QtCore.SIGNAL(_fromUtf8("accepted()")), BinaryDataForm.accept)
        QtCore.QMetaObject.connectSlotsByName(BinaryDataForm)
        BinaryDataForm.setTabOrder(self.raw_data_table_3, self.clear_Btn_3)
        BinaryDataForm.setTabOrder(self.clear_Btn_3, self.back_calc_btn_3)
        BinaryDataForm.setTabOrder(self.back_calc_btn_3, self.effect_cbo_box_3)
        BinaryDataForm.setTabOrder(self.effect_cbo_box_3, self.effect_txt_box_3)
        BinaryDataForm.setTabOrder(self.effect_txt_box_3, self.low_txt_box_3)
        BinaryDataForm.setTabOrder(self.low_txt_box_3, self.high_txt_box_3)
        BinaryDataForm.setTabOrder(self.high_txt_box_3, self.CI_spinbox_3)
        BinaryDataForm.setTabOrder(self.CI_spinbox_3, self.buttonBox_3)

    def retranslateUi(self, BinaryDataForm):
        BinaryDataForm.setWindowTitle(_translate("BinaryDataForm", "Binary Data", None))
        self.event_lbl_3.setText(_translate("BinaryDataForm", "event", None))
        self.label_18.setText(_translate("BinaryDataForm", "no event", None))
        self.label_19.setText(_translate("BinaryDataForm", "total", None))
        self.label_20.setText(_translate("BinaryDataForm", "group 1", None))
        self.label_21.setText(_translate("BinaryDataForm", "group 2", None))
        self.label_22.setText(_translate("BinaryDataForm", "total", None))
        self.clear_Btn_3.setText(_translate("BinaryDataForm", "Clear Form", None))
        self.back_calc_btn_3.setText(_translate("BinaryDataForm", "back-calculate table", None))
        self.label_17.setText(_translate("BinaryDataForm", "effect", None))
        self.ci_label_3.setToolTip(_translate("BinaryDataForm", "Use the box to the left to set the % confidence interval", None))
        self.est_lbl_3.setText(_translate("BinaryDataForm", "est.", None))
        self.low_lbl_3.setText(_translate("BinaryDataForm", "[", None))
        self.label_23.setText(_translate("BinaryDataForm", ",", None))
        self.high_lbl_3.setText(_translate("BinaryDataForm", "]", None))
        self.label_24.setText(_translate("BinaryDataForm", "Confidence Level:", None))
        self.CI_spinbox_3.setToolTip(_translate("BinaryDataForm", "Use this box to set the % confidence interval", None))
        self.CI_spinbox_3.setSuffix(_translate("BinaryDataForm", " %", None))
        self.inconsistencyLabel_3.setText(_translate("BinaryDataForm", "INCONSISTENT FORM", None))

import icons_rc
