# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'continuous_data_form.ui'
#
# Created: Tue Dec 06 11:16:12 2011
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ContinuousDataForm(object):
    def setupUi(self, ContinuousDataForm):
        ContinuousDataForm.setObjectName(_fromUtf8("ContinuousDataForm"))
        ContinuousDataForm.resize(670, 555)
        ContinuousDataForm.setMinimumSize(QtCore.QSize(670, 0))
        ContinuousDataForm.setMaximumSize(QtCore.QSize(670, 555))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        ContinuousDataForm.setFont(font)
        ContinuousDataForm.setWindowTitle(QtGui.QApplication.translate("ContinuousDataForm", "Continuous Data", None, QtGui.QApplication.UnicodeUTF8))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/meta.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ContinuousDataForm.setWindowIcon(icon)
        self.buttonBox = QtGui.QDialogButtonBox(ContinuousDataForm)
        self.buttonBox.setGeometry(QtCore.QRect(470, 520, 181, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.grp_box_pre_post = QtGui.QGroupBox(ContinuousDataForm)
        self.grp_box_pre_post.setGeometry(QtCore.QRect(20, 120, 631, 251))
        self.grp_box_pre_post.setTitle(QtGui.QApplication.translate("ContinuousDataForm", "pre / post", None, QtGui.QApplication.UnicodeUTF8))
        self.grp_box_pre_post.setObjectName(_fromUtf8("grp_box_pre_post"))
        self.grp_1_lbl = QtGui.QLabel(self.grp_box_pre_post)
        self.grp_1_lbl.setGeometry(QtCore.QRect(10, 70, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.grp_1_lbl.setFont(font)
        self.grp_1_lbl.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.grp_1_lbl.setText(QtGui.QApplication.translate("ContinuousDataForm", "group 1", None, QtGui.QApplication.UnicodeUTF8))
        self.grp_1_lbl.setObjectName(_fromUtf8("grp_1_lbl"))
        self.grp_2_lbl = QtGui.QLabel(self.grp_box_pre_post)
        self.grp_2_lbl.setGeometry(QtCore.QRect(10, 170, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.grp_2_lbl.setFont(font)
        self.grp_2_lbl.setText(QtGui.QApplication.translate("ContinuousDataForm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Verdana\'; font-size:8pt; font-weight:600; font-style:italic;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">group 2</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.grp_2_lbl.setObjectName(_fromUtf8("grp_2_lbl"))
        self.g1_pre_post_table = QtGui.QTableWidget(self.grp_box_pre_post)
        self.g1_pre_post_table.setGeometry(QtCore.QRect(70, 31, 490, 81))
        self.g1_pre_post_table.setMinimumSize(QtCore.QSize(490, 0))
        self.g1_pre_post_table.setMaximumSize(QtCore.QSize(490, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.g1_pre_post_table.setFont(font)
        self.g1_pre_post_table.setFrameShape(QtGui.QFrame.NoFrame)
        self.g1_pre_post_table.setFrameShadow(QtGui.QFrame.Plain)
        self.g1_pre_post_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.g1_pre_post_table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.g1_pre_post_table.setAlternatingRowColors(True)
        self.g1_pre_post_table.setShowGrid(True)
        self.g1_pre_post_table.setGridStyle(QtCore.Qt.DashLine)
        self.g1_pre_post_table.setRowCount(2)
        self.g1_pre_post_table.setColumnCount(7)
        self.g1_pre_post_table.setObjectName(_fromUtf8("g1_pre_post_table"))
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("ContinuousDataForm", "pre", None, QtGui.QApplication.UnicodeUTF8))
        self.g1_pre_post_table.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("ContinuousDataForm", "post", None, QtGui.QApplication.UnicodeUTF8))
        self.g1_pre_post_table.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("ContinuousDataForm", "n", None, QtGui.QApplication.UnicodeUTF8))
        self.g1_pre_post_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("ContinuousDataForm", "mean", None, QtGui.QApplication.UnicodeUTF8))
        self.g1_pre_post_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("ContinuousDataForm", "sd", None, QtGui.QApplication.UnicodeUTF8))
        self.g1_pre_post_table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("ContinuousDataForm", "se", None, QtGui.QApplication.UnicodeUTF8))
        self.g1_pre_post_table.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("ContinuousDataForm", "var", None, QtGui.QApplication.UnicodeUTF8))
        self.g1_pre_post_table.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("ContinuousDataForm", "low", None, QtGui.QApplication.UnicodeUTF8))
        self.g1_pre_post_table.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("ContinuousDataForm", "high", None, QtGui.QApplication.UnicodeUTF8))
        self.g1_pre_post_table.setHorizontalHeaderItem(6, item)
        self.g2_pre_post_table = QtGui.QTableWidget(self.grp_box_pre_post)
        self.g2_pre_post_table.setGeometry(QtCore.QRect(70, 130, 490, 81))
        self.g2_pre_post_table.setMinimumSize(QtCore.QSize(490, 0))
        self.g2_pre_post_table.setMaximumSize(QtCore.QSize(490, 16777215))
        self.g2_pre_post_table.setFrameShape(QtGui.QFrame.NoFrame)
        self.g2_pre_post_table.setFrameShadow(QtGui.QFrame.Plain)
        self.g2_pre_post_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.g2_pre_post_table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.g2_pre_post_table.setAlternatingRowColors(True)
        self.g2_pre_post_table.setGridStyle(QtCore.Qt.DashLine)
        self.g2_pre_post_table.setRowCount(2)
        self.g2_pre_post_table.setColumnCount(7)
        self.g2_pre_post_table.setObjectName(_fromUtf8("g2_pre_post_table"))
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("ContinuousDataForm", "pre", None, QtGui.QApplication.UnicodeUTF8))
        self.g2_pre_post_table.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("ContinuousDataForm", "post", None, QtGui.QApplication.UnicodeUTF8))
        self.g2_pre_post_table.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("ContinuousDataForm", "n", None, QtGui.QApplication.UnicodeUTF8))
        self.g2_pre_post_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("ContinuousDataForm", "mean", None, QtGui.QApplication.UnicodeUTF8))
        self.g2_pre_post_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("ContinuousDataForm", "sd", None, QtGui.QApplication.UnicodeUTF8))
        self.g2_pre_post_table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("ContinuousDataForm", "se", None, QtGui.QApplication.UnicodeUTF8))
        self.g2_pre_post_table.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("ContinuousDataForm", "var", None, QtGui.QApplication.UnicodeUTF8))
        self.g2_pre_post_table.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("ContinuousDataForm", "low", None, QtGui.QApplication.UnicodeUTF8))
        self.g2_pre_post_table.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("ContinuousDataForm", "high", None, QtGui.QApplication.UnicodeUTF8))
        self.g2_pre_post_table.setHorizontalHeaderItem(6, item)
        self.label = QtGui.QLabel(self.grp_box_pre_post)
        self.label.setGeometry(QtCore.QRect(450, 220, 71, 16))
        self.label.setText(QtGui.QApplication.translate("ContinuousDataForm", "correlation:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.correlation_pre_post = QtGui.QLineEdit(self.grp_box_pre_post)
        self.correlation_pre_post.setGeometry(QtCore.QRect(530, 220, 41, 16))
        self.correlation_pre_post.setText(QtGui.QApplication.translate("ContinuousDataForm", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.correlation_pre_post.setObjectName(_fromUtf8("correlation_pre_post"))
        self.simple_table = QtGui.QTableWidget(ContinuousDataForm)
        self.simple_table.setGeometry(QtCore.QRect(60, 10, 550, 80))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.simple_table.sizePolicy().hasHeightForWidth())
        self.simple_table.setSizePolicy(sizePolicy)
        self.simple_table.setMinimumSize(QtCore.QSize(550, 80))
        self.simple_table.setMaximumSize(QtCore.QSize(550, 80))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.simple_table.setFont(font)
        self.simple_table.setFrameShape(QtGui.QFrame.NoFrame)
        self.simple_table.setFrameShadow(QtGui.QFrame.Plain)
        self.simple_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.simple_table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.simple_table.setAlternatingRowColors(True)
        self.simple_table.setGridStyle(QtCore.Qt.DashLine)
        self.simple_table.setRowCount(2)
        self.simple_table.setColumnCount(8)
        self.simple_table.setObjectName(_fromUtf8("simple_table"))
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("ContinuousDataForm", "group 1", None, QtGui.QApplication.UnicodeUTF8))
        self.simple_table.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("ContinuousDataForm", "group 2", None, QtGui.QApplication.UnicodeUTF8))
        self.simple_table.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("ContinuousDataForm", "n", None, QtGui.QApplication.UnicodeUTF8))
        self.simple_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("ContinuousDataForm", "mean", None, QtGui.QApplication.UnicodeUTF8))
        self.simple_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("ContinuousDataForm", "sd", None, QtGui.QApplication.UnicodeUTF8))
        self.simple_table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("ContinuousDataForm", "se", None, QtGui.QApplication.UnicodeUTF8))
        self.simple_table.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("ContinuousDataForm", "var", None, QtGui.QApplication.UnicodeUTF8))
        self.simple_table.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("ContinuousDataForm", "pval", None, QtGui.QApplication.UnicodeUTF8))
        self.simple_table.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("ContinuousDataForm", "low", None, QtGui.QApplication.UnicodeUTF8))
        self.simple_table.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("ContinuousDataForm", "high", None, QtGui.QApplication.UnicodeUTF8))
        self.simple_table.setHorizontalHeaderItem(7, item)
        self.label_2 = QtGui.QLabel(ContinuousDataForm)
        self.label_2.setGeometry(QtCore.QRect(20, 470, 16, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setText(QtGui.QApplication.translate("ContinuousDataForm", "α:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.alpha_edit = QtGui.QLineEdit(ContinuousDataForm)
        self.alpha_edit.setGeometry(QtCore.QRect(40, 470, 31, 16))
        self.alpha_edit.setText(QtGui.QApplication.translate("ContinuousDataForm", ".05", None, QtGui.QApplication.UnicodeUTF8))
        self.alpha_edit.setObjectName(_fromUtf8("alpha_edit"))
        self.ci_label = QtGui.QLabel(ContinuousDataForm)
        self.ci_label.setGeometry(QtCore.QRect(80, 470, 251, 16))
        self.ci_label.setText(QtGui.QApplication.translate("ContinuousDataForm", "(95% confidence interval)", None, QtGui.QApplication.UnicodeUTF8))
        self.ci_label.setObjectName(_fromUtf8("ci_label"))
        self.layoutWidget_4 = QtGui.QWidget(ContinuousDataForm)
        self.layoutWidget_4.setGeometry(QtCore.QRect(160, 420, 351, 41))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget_4)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_14 = QtGui.QLabel(self.layoutWidget_4)
        self.label_14.setMinimumSize(QtCore.QSize(0, 20))
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.label_14.setFont(font)
        self.label_14.setText(QtGui.QApplication.translate("ContinuousDataForm", "est.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_3.addWidget(self.label_14, 0, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.layoutWidget_4)
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.label_15.setFont(font)
        self.label_15.setText(QtGui.QApplication.translate("ContinuousDataForm", "low", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_3.addWidget(self.label_15, 0, 2, 1, 1)
        self.label_16 = QtGui.QLabel(self.layoutWidget_4)
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.label_16.setFont(font)
        self.label_16.setText(QtGui.QApplication.translate("ContinuousDataForm", "high", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_3.addWidget(self.label_16, 0, 4, 1, 1)
        self.effect_txt_box = QtGui.QLineEdit(self.layoutWidget_4)
        self.effect_txt_box.setMinimumSize(QtCore.QSize(50, 22))
        self.effect_txt_box.setMaximumSize(QtCore.QSize(50, 22))
        self.effect_txt_box.setObjectName(_fromUtf8("effect_txt_box"))
        self.gridLayout_3.addWidget(self.effect_txt_box, 0, 1, 1, 1)
        self.low_txt_box = QtGui.QLineEdit(self.layoutWidget_4)
        self.low_txt_box.setMinimumSize(QtCore.QSize(50, 22))
        self.low_txt_box.setMaximumSize(QtCore.QSize(50, 22))
        self.low_txt_box.setObjectName(_fromUtf8("low_txt_box"))
        self.gridLayout_3.addWidget(self.low_txt_box, 0, 3, 1, 1)
        self.high_txt_box = QtGui.QLineEdit(self.layoutWidget_4)
        self.high_txt_box.setMinimumSize(QtCore.QSize(50, 22))
        self.high_txt_box.setMaximumSize(QtCore.QSize(50, 22))
        self.high_txt_box.setObjectName(_fromUtf8("high_txt_box"))
        self.gridLayout_3.addWidget(self.high_txt_box, 0, 5, 1, 1)
        self.label_13 = QtGui.QLabel(ContinuousDataForm)
        self.label_13.setGeometry(QtCore.QRect(140, 380, 91, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.label_13.setFont(font)
        self.label_13.setText(QtGui.QApplication.translate("ContinuousDataForm", "effect", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.effect_cbo_box = QtGui.QComboBox(ContinuousDataForm)
        self.effect_cbo_box.setGeometry(QtCore.QRect(190, 390, 76, 20))
        self.effect_cbo_box.setMinimumSize(QtCore.QSize(76, 20))
        self.effect_cbo_box.setMaximumSize(QtCore.QSize(76, 20))
        self.effect_cbo_box.setObjectName(_fromUtf8("effect_cbo_box"))

        self.retranslateUi(ContinuousDataForm)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ContinuousDataForm.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ContinuousDataForm.reject)
        QtCore.QMetaObject.connectSlotsByName(ContinuousDataForm)

    def retranslateUi(self, ContinuousDataForm):
        item = self.g1_pre_post_table.verticalHeaderItem(0)
        item = self.g1_pre_post_table.verticalHeaderItem(1)
        item = self.g1_pre_post_table.horizontalHeaderItem(0)
        item = self.g1_pre_post_table.horizontalHeaderItem(1)
        item = self.g1_pre_post_table.horizontalHeaderItem(2)
        item = self.g1_pre_post_table.horizontalHeaderItem(3)
        item = self.g1_pre_post_table.horizontalHeaderItem(4)
        item = self.g1_pre_post_table.horizontalHeaderItem(5)
        item = self.g1_pre_post_table.horizontalHeaderItem(6)
        item = self.g2_pre_post_table.verticalHeaderItem(0)
        item = self.g2_pre_post_table.verticalHeaderItem(1)
        item = self.g2_pre_post_table.horizontalHeaderItem(0)
        item = self.g2_pre_post_table.horizontalHeaderItem(1)
        item = self.g2_pre_post_table.horizontalHeaderItem(2)
        item = self.g2_pre_post_table.horizontalHeaderItem(3)
        item = self.g2_pre_post_table.horizontalHeaderItem(4)
        item = self.g2_pre_post_table.horizontalHeaderItem(5)
        item = self.g2_pre_post_table.horizontalHeaderItem(6)
        item = self.simple_table.verticalHeaderItem(0)
        item = self.simple_table.verticalHeaderItem(1)
        item = self.simple_table.horizontalHeaderItem(0)
        item = self.simple_table.horizontalHeaderItem(1)
        item = self.simple_table.horizontalHeaderItem(2)
        item = self.simple_table.horizontalHeaderItem(3)
        item = self.simple_table.horizontalHeaderItem(4)
        item = self.simple_table.horizontalHeaderItem(5)
        item = self.simple_table.horizontalHeaderItem(6)
        item = self.simple_table.horizontalHeaderItem(7)

import icons_rc
