# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create_new_projectdlg.ui'
#
# Created: Mon Feb 25 15:16:32 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_newprojectdialog(object):
    def setupUi(self, newprojectdialog):
        newprojectdialog.setObjectName(_fromUtf8("newprojectdialog"))
        newprojectdialog.setEnabled(True)
        newprojectdialog.resize(504, 541)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(newprojectdialog.sizePolicy().hasHeightForWidth())
        newprojectdialog.setSizePolicy(sizePolicy)
        newprojectdialog.setSizeGripEnabled(True)
        newprojectdialog.setModal(False)
        self.verticalLayout = QtGui.QVBoxLayout(newprojectdialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.what_type_of_data_Label = QtGui.QLabel(newprojectdialog)
        self.what_type_of_data_Label.setMinimumSize(QtCore.QSize(281, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Comic Sans MS"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.what_type_of_data_Label.setFont(font)
        self.what_type_of_data_Label.setObjectName(_fromUtf8("what_type_of_data_Label"))
        self.verticalLayout.addWidget(self.what_type_of_data_Label)
        self.groupBox = QtGui.QGroupBox(newprojectdialog)
        self.groupBox.setMinimumSize(QtCore.QSize(480, 0))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.onearm_single_reg_coef_Button = QtGui.QToolButton(self.groupBox)
        self.onearm_single_reg_coef_Button.setMinimumSize(QtCore.QSize(90, 65))
        self.onearm_single_reg_coef_Button.setMaximumSize(QtCore.QSize(90, 65))
        self.onearm_single_reg_coef_Button.setBaseSize(QtCore.QSize(10, 10))
        self.onearm_single_reg_coef_Button.setCheckable(True)
        self.onearm_single_reg_coef_Button.setObjectName(_fromUtf8("onearm_single_reg_coef_Button"))
        self.buttonGroup = QtGui.QButtonGroup(newprojectdialog)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.onearm_single_reg_coef_Button)
        self.gridLayout.addWidget(self.onearm_single_reg_coef_Button, 1, 2, 1, 1)
        self.twoarm_smds_Button = QtGui.QToolButton(self.groupBox)
        self.twoarm_smds_Button.setMinimumSize(QtCore.QSize(90, 65))
        self.twoarm_smds_Button.setMaximumSize(QtCore.QSize(90, 65))
        self.twoarm_smds_Button.setBaseSize(QtCore.QSize(10, 10))
        self.twoarm_smds_Button.setCheckable(True)
        self.twoarm_smds_Button.setObjectName(_fromUtf8("twoarm_smds_Button"))
        self.buttonGroup.addButton(self.twoarm_smds_Button)
        self.gridLayout.addWidget(self.twoarm_smds_Button, 5, 2, 1, 1)
        self.onearm_generic_effect_size_Button = QtGui.QToolButton(self.groupBox)
        self.onearm_generic_effect_size_Button.setMinimumSize(QtCore.QSize(90, 65))
        self.onearm_generic_effect_size_Button.setMaximumSize(QtCore.QSize(90, 65))
        self.onearm_generic_effect_size_Button.setBaseSize(QtCore.QSize(10, 10))
        self.onearm_generic_effect_size_Button.setCheckable(True)
        self.onearm_generic_effect_size_Button.setArrowType(QtCore.Qt.NoArrow)
        self.onearm_generic_effect_size_Button.setObjectName(_fromUtf8("onearm_generic_effect_size_Button"))
        self.buttonGroup.addButton(self.onearm_generic_effect_size_Button)
        self.gridLayout.addWidget(self.onearm_generic_effect_size_Button, 1, 3, 1, 1)
        self.onearm_mean_Button = QtGui.QToolButton(self.groupBox)
        self.onearm_mean_Button.setMinimumSize(QtCore.QSize(90, 65))
        self.onearm_mean_Button.setMaximumSize(QtCore.QSize(90, 65))
        self.onearm_mean_Button.setBaseSize(QtCore.QSize(10, 10))
        self.onearm_mean_Button.setCheckable(True)
        self.onearm_mean_Button.setObjectName(_fromUtf8("onearm_mean_Button"))
        self.buttonGroup.addButton(self.onearm_mean_Button)
        self.gridLayout.addWidget(self.onearm_mean_Button, 1, 1, 1, 1)
        self.onearm_proportion_Button = QtGui.QToolButton(self.groupBox)
        self.onearm_proportion_Button.setMinimumSize(QtCore.QSize(90, 65))
        self.onearm_proportion_Button.setMaximumSize(QtCore.QSize(90, 65))
        self.onearm_proportion_Button.setBaseSize(QtCore.QSize(10, 10))
        self.onearm_proportion_Button.setCheckable(True)
        self.onearm_proportion_Button.setChecked(False)
        self.onearm_proportion_Button.setObjectName(_fromUtf8("onearm_proportion_Button"))
        self.buttonGroup.addButton(self.onearm_proportion_Button)
        self.gridLayout.addWidget(self.onearm_proportion_Button, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 3)
        self.twoarm_proportions_Button = QtGui.QToolButton(self.groupBox)
        self.twoarm_proportions_Button.setMinimumSize(QtCore.QSize(90, 65))
        self.twoarm_proportions_Button.setMaximumSize(QtCore.QSize(90, 65))
        self.twoarm_proportions_Button.setBaseSize(QtCore.QSize(10, 10))
        self.twoarm_proportions_Button.setCheckable(True)
        self.twoarm_proportions_Button.setObjectName(_fromUtf8("twoarm_proportions_Button"))
        self.buttonGroup.addButton(self.twoarm_proportions_Button)
        self.gridLayout.addWidget(self.twoarm_proportions_Button, 5, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 7, 0, 1, 2)
        self.diagnostic_Button = QtGui.QToolButton(self.groupBox)
        self.diagnostic_Button.setMinimumSize(QtCore.QSize(90, 65))
        self.diagnostic_Button.setMaximumSize(QtCore.QSize(90, 65))
        self.diagnostic_Button.setBaseSize(QtCore.QSize(10, 10))
        self.diagnostic_Button.setCheckable(True)
        self.diagnostic_Button.setObjectName(_fromUtf8("diagnostic_Button"))
        self.buttonGroup.addButton(self.diagnostic_Button)
        self.gridLayout.addWidget(self.diagnostic_Button, 8, 0, 1, 1)
        self.line_4 = QtGui.QFrame(self.groupBox)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout.addWidget(self.line_4, 6, 0, 1, 6)
        self.line_2 = QtGui.QFrame(self.groupBox)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 2, 0, 1, 6)
        self.twoarm_means_Button = QtGui.QToolButton(self.groupBox)
        self.twoarm_means_Button.setMinimumSize(QtCore.QSize(90, 65))
        self.twoarm_means_Button.setMaximumSize(QtCore.QSize(90, 65))
        self.twoarm_means_Button.setBaseSize(QtCore.QSize(10, 10))
        self.twoarm_means_Button.setCheckable(True)
        self.twoarm_means_Button.setObjectName(_fromUtf8("twoarm_means_Button"))
        self.buttonGroup.addButton(self.twoarm_means_Button)
        self.gridLayout.addWidget(self.twoarm_means_Button, 5, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 5)
        self.verticalLayout.addWidget(self.groupBox)
        self.outcome_name_Frame = QtGui.QFrame(newprojectdialog)
        self.outcome_name_Frame.setEnabled(True)
        self.outcome_name_Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.outcome_name_Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.outcome_name_Frame.setObjectName(_fromUtf8("outcome_name_Frame"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.outcome_name_Frame)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.outcome_name_Frame)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.outcome_name_LineEdit = QtGui.QLineEdit(self.outcome_name_Frame)
        self.outcome_name_LineEdit.setEnabled(False)
        self.outcome_name_LineEdit.setText(_fromUtf8(""))
        self.outcome_name_LineEdit.setObjectName(_fromUtf8("outcome_name_LineEdit"))
        self.horizontalLayout_2.addWidget(self.outcome_name_LineEdit)
        self.verticalLayout.addWidget(self.outcome_name_Frame)
        self.buttonBox = QtGui.QDialogButtonBox(newprojectdialog)
        self.buttonBox.setEnabled(False)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)
        self.helpLabel = QtGui.QLabel(newprojectdialog)
        self.helpLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.helpLabel.setOpenExternalLinks(True)
        self.helpLabel.setObjectName(_fromUtf8("helpLabel"))
        self.verticalLayout.addWidget(self.helpLabel)
        self.label.setBuddy(self.outcome_name_LineEdit)

        self.retranslateUi(newprojectdialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), newprojectdialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), newprojectdialog.reject)
        QtCore.QMetaObject.connectSlotsByName(newprojectdialog)

    def retranslateUi(self, newprojectdialog):
        newprojectdialog.setWindowTitle(_translate("newprojectdialog", "Dialog", None))
        self.what_type_of_data_Label.setText(_translate("newprojectdialog", "WHAT TYPE OF DATA DO YOU HAVE?", None))
        self.onearm_single_reg_coef_Button.setText(_translate("newprojectdialog", "single regression\n"
"coefficient", None))
        self.twoarm_smds_Button.setText(_translate("newprojectdialog", "Standardized\n"
"mean differences", None))
        self.onearm_generic_effect_size_Button.setText(_translate("newprojectdialog", "generic\n"
"effect size", None))
        self.onearm_mean_Button.setText(_translate("newprojectdialog", "mean", None))
        self.onearm_proportion_Button.setText(_translate("newprojectdialog", "proportion", None))
        self.label_4.setText(_translate("newprojectdialog", "Data on two or more groups per study", None))
        self.twoarm_proportions_Button.setText(_translate("newprojectdialog", "proportions", None))
        self.label_5.setText(_translate("newprojectdialog", "Data on test performance", None))
        self.diagnostic_Button.setText(_translate("newprojectdialog", "diagnostic", None))
        self.twoarm_means_Button.setText(_translate("newprojectdialog", "means", None))
        self.label_2.setText(_translate("newprojectdialog", "One piece of data from each study or studies with one group", None))
        self.label.setText(_translate("newprojectdialog", "What is the name of your outcome?", None))
        self.helpLabel.setText(_translate("newprojectdialog", "<a href=\"http://tuftscaes.org/open_meta/help/openMA_help.html\">help</a>", None))

import icons_rc
