# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'continuous_data_form.ui'
#
# Created: Mon Apr 05 16:21:59 2010
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_ContinuousDataForm(object):
    def setupUi(self, ContinuousDataForm):
        ContinuousDataForm.setObjectName("ContinuousDataForm")
        ContinuousDataForm.resize(730, 383)
        ContinuousDataForm.setMinimumSize(QtCore.QSize(730, 0))
        ContinuousDataForm.setMaximumSize(QtCore.QSize(730, 452))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        ContinuousDataForm.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/meta.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ContinuousDataForm.setWindowIcon(icon)
        self.buttonBox = QtGui.QDialogButtonBox(ContinuousDataForm)
        self.buttonBox.setGeometry(QtCore.QRect(540, 340, 181, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.grp_box_pre_post = QtGui.QGroupBox(ContinuousDataForm)
        self.grp_box_pre_post.setGeometry(QtCore.QRect(10, 110, 711, 221))
        self.grp_box_pre_post.setObjectName("grp_box_pre_post")
        self.label_8 = QtGui.QLabel(self.grp_box_pre_post)
        self.label_8.setGeometry(QtCore.QRect(10, 60, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtGui.QLabel(self.grp_box_pre_post)
        self.label_9.setGeometry(QtCore.QRect(10, 160, 46, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.pre_table = QtGui.QTableWidget(self.grp_box_pre_post)
        self.pre_table.setGeometry(QtCore.QRect(40, 21, 661, 91))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.pre_table.setFont(font)
        self.pre_table.setFrameShape(QtGui.QFrame.NoFrame)
        self.pre_table.setFrameShadow(QtGui.QFrame.Plain)
        self.pre_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pre_table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pre_table.setAlternatingRowColors(False)
        self.pre_table.setShowGrid(True)
        self.pre_table.setGridStyle(QtCore.Qt.DashLine)
        self.pre_table.setRowCount(2)
        self.pre_table.setColumnCount(6)
        self.pre_table.setObjectName("pre_table")
        self.pre_table.setColumnCount(6)
        self.pre_table.setRowCount(2)
        item = QtGui.QTableWidgetItem()
        self.pre_table.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.pre_table.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.pre_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.pre_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.pre_table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.pre_table.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.pre_table.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.pre_table.setHorizontalHeaderItem(5, item)
        self.pre_table_2 = QtGui.QTableWidget(self.grp_box_pre_post)
        self.pre_table_2.setGeometry(QtCore.QRect(40, 120, 661, 91))
        self.pre_table_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.pre_table_2.setFrameShadow(QtGui.QFrame.Plain)
        self.pre_table_2.setGridStyle(QtCore.Qt.DashLine)
        self.pre_table_2.setRowCount(2)
        self.pre_table_2.setColumnCount(6)
        self.pre_table_2.setObjectName("pre_table_2")
        self.pre_table_2.setColumnCount(6)
        self.pre_table_2.setRowCount(2)
        item = QtGui.QTableWidgetItem()
        self.pre_table_2.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.pre_table_2.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.pre_table_2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.pre_table_2.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.pre_table_2.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.pre_table_2.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.pre_table_2.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.pre_table_2.setHorizontalHeaderItem(5, item)
        self.std_table = QtGui.QTableWidget(ContinuousDataForm)
        self.std_table.setGeometry(QtCore.QRect(40, 20, 651, 80))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.std_table.sizePolicy().hasHeightForWidth())
        self.std_table.setSizePolicy(sizePolicy)
        self.std_table.setMinimumSize(QtCore.QSize(500, 80))
        self.std_table.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.std_table.setFont(font)
        self.std_table.setFrameShape(QtGui.QFrame.NoFrame)
        self.std_table.setFrameShadow(QtGui.QFrame.Plain)
        self.std_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.std_table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.std_table.setGridStyle(QtCore.Qt.DashLine)
        self.std_table.setRowCount(2)
        self.std_table.setColumnCount(6)
        self.std_table.setObjectName("std_table")
        self.std_table.setColumnCount(6)
        self.std_table.setRowCount(2)
        item = QtGui.QTableWidgetItem()
        self.std_table.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.std_table.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.std_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.std_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.std_table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.std_table.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.std_table.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.std_table.setHorizontalHeaderItem(5, item)

        self.retranslateUi(ContinuousDataForm)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), ContinuousDataForm.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), ContinuousDataForm.reject)
        QtCore.QMetaObject.connectSlotsByName(ContinuousDataForm)

    def retranslateUi(self, ContinuousDataForm):
        ContinuousDataForm.setWindowTitle(QtGui.QApplication.translate("ContinuousDataForm", "Continuous Data", None, QtGui.QApplication.UnicodeUTF8))
        self.grp_box_pre_post.setTitle(QtGui.QApplication.translate("ContinuousDataForm", "pre / post", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("ContinuousDataForm", "pre", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("ContinuousDataForm", "post", None, QtGui.QApplication.UnicodeUTF8))
        self.pre_table.verticalHeaderItem(0).setText(QtGui.QApplication.translate("ContinuousDataForm", "group 1", None, QtGui.QApplication.UnicodeUTF8))
        self.pre_table.verticalHeaderItem(1).setText(QtGui.QApplication.translate("ContinuousDataForm", "group 2", None, QtGui.QApplication.UnicodeUTF8))
        self.pre_table.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("ContinuousDataForm", "n (pre)", None, QtGui.QApplication.UnicodeUTF8))
        self.pre_table.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("ContinuousDataForm", "mean (pre)", None, QtGui.QApplication.UnicodeUTF8))
        self.pre_table.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("ContinuousDataForm", "sd (pre)", None, QtGui.QApplication.UnicodeUTF8))
        self.pre_table.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("ContinuousDataForm", "se (pre)", None, QtGui.QApplication.UnicodeUTF8))
        self.pre_table.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("ContinuousDataForm", "var (pre)", None, QtGui.QApplication.UnicodeUTF8))
        self.pre_table.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("ContinuousDataForm", "p-val (pre)", None, QtGui.QApplication.UnicodeUTF8))
        self.pre_table_2.verticalHeaderItem(0).setText(QtGui.QApplication.translate("ContinuousDataForm", "group 1", None, QtGui.QApplication.UnicodeUTF8))
        self.pre_table_2.verticalHeaderItem(1).setText(QtGui.QApplication.translate("ContinuousDataForm", "group 2", None, QtGui.QApplication.UnicodeUTF8))
        self.pre_table_2.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("ContinuousDataForm", "n (post)", None, QtGui.QApplication.UnicodeUTF8))
        self.pre_table_2.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("ContinuousDataForm", "mean (post)", None, QtGui.QApplication.UnicodeUTF8))
        self.pre_table_2.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("ContinuousDataForm", "sd (post)", None, QtGui.QApplication.UnicodeUTF8))
        self.pre_table_2.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("ContinuousDataForm", "se (post)", None, QtGui.QApplication.UnicodeUTF8))
        self.pre_table_2.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("ContinuousDataForm", "var (post)", None, QtGui.QApplication.UnicodeUTF8))
        self.pre_table_2.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("ContinuousDataForm", "p-val (post)", None, QtGui.QApplication.UnicodeUTF8))
        self.std_table.verticalHeaderItem(0).setText(QtGui.QApplication.translate("ContinuousDataForm", "group 1", None, QtGui.QApplication.UnicodeUTF8))
        self.std_table.verticalHeaderItem(1).setText(QtGui.QApplication.translate("ContinuousDataForm", "group 2", None, QtGui.QApplication.UnicodeUTF8))
        self.std_table.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("ContinuousDataForm", "n", None, QtGui.QApplication.UnicodeUTF8))
        self.std_table.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("ContinuousDataForm", "mean", None, QtGui.QApplication.UnicodeUTF8))
        self.std_table.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("ContinuousDataForm", "sd", None, QtGui.QApplication.UnicodeUTF8))
        self.std_table.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("ContinuousDataForm", "se", None, QtGui.QApplication.UnicodeUTF8))
        self.std_table.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("ContinuousDataForm", "var", None, QtGui.QApplication.UnicodeUTF8))
        self.std_table.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("ContinuousDataForm", "p-val", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
