# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'diagnostic_data_form.ui'
#
# Created: Fri Apr 12 15:38:25 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DiagnosticDataForm(object):
    def setupUi(self, DiagnosticDataForm):
        DiagnosticDataForm.setObjectName(_fromUtf8("DiagnosticDataForm"))
        DiagnosticDataForm.resize(380, 449)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/meta.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DiagnosticDataForm.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(DiagnosticDataForm)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.two_by_two_table = QtGui.QTableWidget(DiagnosticDataForm)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.two_by_two_table.sizePolicy().hasHeightForWidth())
        self.two_by_two_table.setSizePolicy(sizePolicy)
        self.two_by_two_table.setMinimumSize(QtCore.QSize(356, 111))
        self.two_by_two_table.setMaximumSize(QtCore.QSize(356, 111))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.two_by_two_table.setFont(font)
        self.two_by_two_table.setFrameShape(QtGui.QFrame.NoFrame)
        self.two_by_two_table.setFrameShadow(QtGui.QFrame.Plain)
        self.two_by_two_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.two_by_two_table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.two_by_two_table.setAlternatingRowColors(True)
        self.two_by_two_table.setGridStyle(QtCore.Qt.DashLine)
        self.two_by_two_table.setRowCount(3)
        self.two_by_two_table.setColumnCount(3)
        self.two_by_two_table.setObjectName(_fromUtf8("two_by_two_table"))
        item = QtGui.QTableWidgetItem()
        self.two_by_two_table.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.two_by_two_table.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.two_by_two_table.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.two_by_two_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.two_by_two_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.two_by_two_table.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.two_by_two_table)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.clear_Btn = QtGui.QPushButton(DiagnosticDataForm)
        self.clear_Btn.setObjectName(_fromUtf8("clear_Btn"))
        self.horizontalLayout_6.addWidget(self.clear_Btn)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.back_calc_Btn = QtGui.QPushButton(DiagnosticDataForm)
        self.back_calc_Btn.setEnabled(False)
        self.back_calc_Btn.setObjectName(_fromUtf8("back_calc_Btn"))
        self.horizontalLayout_6.addWidget(self.back_calc_Btn)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.prevalence_lbl = QtGui.QLabel(DiagnosticDataForm)
        self.prevalence_lbl.setObjectName(_fromUtf8("prevalence_lbl"))
        self.horizontalLayout_3.addWidget(self.prevalence_lbl)
        self.prevalence_txt_box = QtGui.QLineEdit(DiagnosticDataForm)
        self.prevalence_txt_box.setMinimumSize(QtCore.QSize(75, 0))
        self.prevalence_txt_box.setMaximumSize(QtCore.QSize(75, 16777215))
        self.prevalence_txt_box.setObjectName(_fromUtf8("prevalence_txt_box"))
        self.horizontalLayout_3.addWidget(self.prevalence_txt_box)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_13 = QtGui.QLabel(DiagnosticDataForm)
        self.label_13.setMinimumSize(QtCore.QSize(50, 0))
        self.label_13.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_2.addWidget(self.label_13)
        self.effect_cbo_box = QtGui.QComboBox(DiagnosticDataForm)
        self.effect_cbo_box.setMinimumSize(QtCore.QSize(100, 20))
        self.effect_cbo_box.setMaximumSize(QtCore.QSize(76, 20))
        self.effect_cbo_box.setObjectName(_fromUtf8("effect_cbo_box"))
        self.horizontalLayout_2.addWidget(self.effect_cbo_box)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.groupBox = QtGui.QGroupBox(DiagnosticDataForm)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem4 = QtGui.QSpacerItem(26, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 0, 2, 1)
        self.ci_label = QtGui.QLabel(self.groupBox)
        self.ci_label.setObjectName(_fromUtf8("ci_label"))
        self.gridLayout.addWidget(self.ci_label, 0, 2, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(26, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 0, 3, 2, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_14 = QtGui.QLabel(self.groupBox)
        self.label_14.setMinimumSize(QtCore.QSize(0, 20))
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_7.addWidget(self.label_14)
        self.effect_txt_box = QtGui.QLineEdit(self.groupBox)
        self.effect_txt_box.setMinimumSize(QtCore.QSize(50, 20))
        self.effect_txt_box.setMaximumSize(QtCore.QSize(50, 20))
        self.effect_txt_box.setObjectName(_fromUtf8("effect_txt_box"))
        self.horizontalLayout_7.addWidget(self.effect_txt_box)
        self.gridLayout.addLayout(self.horizontalLayout_7, 1, 1, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_5.addWidget(self.label)
        self.low_txt_box = QtGui.QLineEdit(self.groupBox)
        self.low_txt_box.setMinimumSize(QtCore.QSize(50, 20))
        self.low_txt_box.setMaximumSize(QtCore.QSize(50, 20))
        self.low_txt_box.setObjectName(_fromUtf8("low_txt_box"))
        self.horizontalLayout_5.addWidget(self.low_txt_box)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_5.addWidget(self.label_4)
        self.high_txt_box = QtGui.QLineEdit(self.groupBox)
        self.high_txt_box.setMinimumSize(QtCore.QSize(50, 20))
        self.high_txt_box.setMaximumSize(QtCore.QSize(50, 20))
        self.high_txt_box.setObjectName(_fromUtf8("high_txt_box"))
        self.horizontalLayout_5.addWidget(self.high_txt_box)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_5.addWidget(self.label_3)
        self.gridLayout.addLayout(self.horizontalLayout_5, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.line = QtGui.QFrame(DiagnosticDataForm)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_2 = QtGui.QLabel(DiagnosticDataForm)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.CI_spinbox = QtGui.QDoubleSpinBox(DiagnosticDataForm)
        self.CI_spinbox.setDecimals(1)
        self.CI_spinbox.setMinimum(40.0)
        self.CI_spinbox.setMaximum(100.0)
        self.CI_spinbox.setSingleStep(0.1)
        self.CI_spinbox.setProperty("value", 95.0)
        self.CI_spinbox.setObjectName(_fromUtf8("CI_spinbox"))
        self.horizontalLayout.addWidget(self.CI_spinbox)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.inconsistencyLabel = QtGui.QLabel(DiagnosticDataForm)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.inconsistencyLabel.setFont(font)
        self.inconsistencyLabel.setObjectName(_fromUtf8("inconsistencyLabel"))
        self.horizontalLayout_4.addWidget(self.inconsistencyLabel)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.buttonBox = QtGui.QDialogButtonBox(DiagnosticDataForm)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout_4.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.prevalence_lbl.setBuddy(self.prevalence_txt_box)

        self.retranslateUi(DiagnosticDataForm)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), DiagnosticDataForm.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), DiagnosticDataForm.reject)
        QtCore.QMetaObject.connectSlotsByName(DiagnosticDataForm)
        DiagnosticDataForm.setTabOrder(self.two_by_two_table, self.clear_Btn)
        DiagnosticDataForm.setTabOrder(self.clear_Btn, self.back_calc_Btn)
        DiagnosticDataForm.setTabOrder(self.back_calc_Btn, self.prevalence_txt_box)
        DiagnosticDataForm.setTabOrder(self.prevalence_txt_box, self.effect_cbo_box)
        DiagnosticDataForm.setTabOrder(self.effect_cbo_box, self.CI_spinbox)
        DiagnosticDataForm.setTabOrder(self.CI_spinbox, self.buttonBox)

    def retranslateUi(self, DiagnosticDataForm):
        DiagnosticDataForm.setWindowTitle(_translate("DiagnosticDataForm", "Dialog", None))
        item = self.two_by_two_table.verticalHeaderItem(0)
        item.setText(_translate("DiagnosticDataForm", "(test) +", None))
        item = self.two_by_two_table.verticalHeaderItem(1)
        item.setText(_translate("DiagnosticDataForm", "(test) -", None))
        item = self.two_by_two_table.verticalHeaderItem(2)
        item.setText(_translate("DiagnosticDataForm", "total", None))
        item = self.two_by_two_table.horizontalHeaderItem(0)
        item.setText(_translate("DiagnosticDataForm", "(disease) +", None))
        item = self.two_by_two_table.horizontalHeaderItem(1)
        item.setText(_translate("DiagnosticDataForm", "(disease) -", None))
        item = self.two_by_two_table.horizontalHeaderItem(2)
        item.setText(_translate("DiagnosticDataForm", "total", None))
        self.clear_Btn.setText(_translate("DiagnosticDataForm", "Clear Form", None))
        self.back_calc_Btn.setText(_translate("DiagnosticDataForm", "back-calculate table", None))
        self.prevalence_lbl.setText(_translate("DiagnosticDataForm", "Prevalence", None))
        self.label_13.setText(_translate("DiagnosticDataForm", "metric", None))
        self.ci_label.setToolTip(_translate("DiagnosticDataForm", "Use the box to the left to set the % confidence interval", None))
        self.ci_label.setText(_translate("DiagnosticDataForm", "X% Confidence Interval", None))
        self.label_14.setText(_translate("DiagnosticDataForm", "est.", None))
        self.label.setText(_translate("DiagnosticDataForm", "[", None))
        self.label_4.setText(_translate("DiagnosticDataForm", ",", None))
        self.label_3.setText(_translate("DiagnosticDataForm", "]", None))
        self.label_2.setText(_translate("DiagnosticDataForm", "Confidence Level:", None))
        self.CI_spinbox.setToolTip(_translate("DiagnosticDataForm", "Use this box to set the % confidence interval", None))
        self.CI_spinbox.setSuffix(_translate("DiagnosticDataForm", " %", None))
        self.inconsistencyLabel.setText(_translate("DiagnosticDataForm", "INCONSISTENT FORM", None))

import icons_rc
