# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_dialog2.ui'
#
# Created: Wed Nov 03 09:21:07 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_edit_dialog(object):
    def setupUi(self, edit_dialog):
        edit_dialog.setObjectName("edit_dialog")
        edit_dialog.resize(571, 378)
        self.verticalLayout = QtGui.QVBoxLayout(edit_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.edit_tab = QtGui.QTabWidget(edit_dialog)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.edit_tab.setFont(font)
        self.edit_tab.setObjectName("edit_tab")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtGui.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.outcome_list = QtGui.QListView(self.groupBox_2)
        self.outcome_list.setGeometry(QtCore.QRect(0, 20, 171, 209))
        self.outcome_list.setAlternatingRowColors(True)
        self.outcome_list.setObjectName("outcome_list")
        self.add_outcome_btn = QtGui.QPushButton(self.groupBox_2)
        self.add_outcome_btn.setGeometry(QtCore.QRect(50, 230, 32, 32))
        self.add_outcome_btn.setMinimumSize(QtCore.QSize(32, 32))
        self.add_outcome_btn.setMaximumSize(QtCore.QSize(32, 32))
        self.add_outcome_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/function_icon_set/add_48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_outcome_btn.setIcon(icon)
        self.add_outcome_btn.setIconSize(QtCore.QSize(32, 32))
        self.add_outcome_btn.setObjectName("add_outcome_btn")
        self.remove_outcome_btn = QtGui.QPushButton(self.groupBox_2)
        self.remove_outcome_btn.setEnabled(False)
        self.remove_outcome_btn.setGeometry(QtCore.QRect(90, 230, 32, 32))
        self.remove_outcome_btn.setMinimumSize(QtCore.QSize(32, 32))
        self.remove_outcome_btn.setMaximumSize(QtCore.QSize(32, 32))
        self.remove_outcome_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/function_icon_set/cancel_48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.remove_outcome_btn.setIcon(icon1)
        self.remove_outcome_btn.setIconSize(QtCore.QSize(32, 32))
        self.remove_outcome_btn.setObjectName("remove_outcome_btn")
        self.gridLayout.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.grpbox_follow_ups = QtGui.QGroupBox(self.tab)
        self.grpbox_follow_ups.setObjectName("grpbox_follow_ups")
        self.follow_up_list = QtGui.QListView(self.grpbox_follow_ups)
        self.follow_up_list.setGeometry(QtCore.QRect(0, 20, 171, 209))
        self.follow_up_list.setAlternatingRowColors(True)
        self.follow_up_list.setObjectName("follow_up_list")
        self.remove_follow_up_btn = QtGui.QPushButton(self.grpbox_follow_ups)
        self.remove_follow_up_btn.setEnabled(False)
        self.remove_follow_up_btn.setGeometry(QtCore.QRect(90, 230, 32, 32))
        self.remove_follow_up_btn.setMinimumSize(QtCore.QSize(32, 32))
        self.remove_follow_up_btn.setMaximumSize(QtCore.QSize(32, 32))
        self.remove_follow_up_btn.setText("")
        self.remove_follow_up_btn.setIcon(icon1)
        self.remove_follow_up_btn.setIconSize(QtCore.QSize(32, 32))
        self.remove_follow_up_btn.setObjectName("remove_follow_up_btn")
        self.add_follow_up_btn = QtGui.QPushButton(self.grpbox_follow_ups)
        self.add_follow_up_btn.setGeometry(QtCore.QRect(50, 230, 32, 32))
        self.add_follow_up_btn.setMinimumSize(QtCore.QSize(32, 32))
        self.add_follow_up_btn.setMaximumSize(QtCore.QSize(32, 32))
        self.add_follow_up_btn.setText("")
        self.add_follow_up_btn.setIcon(icon)
        self.add_follow_up_btn.setIconSize(QtCore.QSize(32, 32))
        self.add_follow_up_btn.setObjectName("add_follow_up_btn")
        self.gridLayout.addWidget(self.grpbox_follow_ups, 0, 1, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.group_list = QtGui.QListView(self.groupBox)
        self.group_list.setGeometry(QtCore.QRect(0, 20, 171, 211))
        self.group_list.setAlternatingRowColors(True)
        self.group_list.setObjectName("group_list")
        self.add_group_btn = QtGui.QPushButton(self.groupBox)
        self.add_group_btn.setGeometry(QtCore.QRect(50, 230, 32, 32))
        self.add_group_btn.setMinimumSize(QtCore.QSize(32, 32))
        self.add_group_btn.setMaximumSize(QtCore.QSize(32, 32))
        self.add_group_btn.setText("")
        self.add_group_btn.setIcon(icon)
        self.add_group_btn.setIconSize(QtCore.QSize(32, 32))
        self.add_group_btn.setObjectName("add_group_btn")
        self.remove_group_btn = QtGui.QPushButton(self.groupBox)
        self.remove_group_btn.setEnabled(False)
        self.remove_group_btn.setGeometry(QtCore.QRect(90, 230, 32, 32))
        self.remove_group_btn.setMinimumSize(QtCore.QSize(32, 32))
        self.remove_group_btn.setMaximumSize(QtCore.QSize(32, 32))
        self.remove_group_btn.setText("")
        self.remove_group_btn.setIcon(icon1)
        self.remove_group_btn.setIconSize(QtCore.QSize(32, 32))
        self.remove_group_btn.setObjectName("remove_group_btn")
        self.gridLayout.addWidget(self.groupBox, 0, 2, 1, 1)
        self.edit_tab.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.study_list = QtGui.QListView(self.tab_2)
        self.study_list.setAlternatingRowColors(True)
        self.study_list.setObjectName("study_list")
        self.gridLayout_2.addWidget(self.study_list, 0, 0, 1, 3)
        self.add_study_btn = QtGui.QPushButton(self.tab_2)
        self.add_study_btn.setMinimumSize(QtCore.QSize(32, 32))
        self.add_study_btn.setMaximumSize(QtCore.QSize(32, 32))
        self.add_study_btn.setText("")
        self.add_study_btn.setIcon(icon)
        self.add_study_btn.setIconSize(QtCore.QSize(32, 32))
        self.add_study_btn.setObjectName("add_study_btn")
        self.gridLayout_2.addWidget(self.add_study_btn, 1, 0, 1, 1)
        self.remove_study_btn = QtGui.QPushButton(self.tab_2)
        self.remove_study_btn.setEnabled(False)
        self.remove_study_btn.setMinimumSize(QtCore.QSize(32, 32))
        self.remove_study_btn.setMaximumSize(QtCore.QSize(32, 32))
        self.remove_study_btn.setText("")
        self.remove_study_btn.setIcon(icon1)
        self.remove_study_btn.setIconSize(QtCore.QSize(32, 32))
        self.remove_study_btn.setObjectName("remove_study_btn")
        self.gridLayout_2.addWidget(self.remove_study_btn, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.edit_tab.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout = QtGui.QHBoxLayout(self.tab_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.covariate_list = QtGui.QListView(self.tab_3)
        self.covariate_list.setAlternatingRowColors(True)
        self.covariate_list.setObjectName("covariate_list")
        self.gridLayout_3.addWidget(self.covariate_list, 0, 0, 1, 3)
        self.add_covariate_btn = QtGui.QPushButton(self.tab_3)
        self.add_covariate_btn.setMinimumSize(QtCore.QSize(32, 32))
        self.add_covariate_btn.setMaximumSize(QtCore.QSize(32, 32))
        self.add_covariate_btn.setText("")
        self.add_covariate_btn.setIcon(icon)
        self.add_covariate_btn.setIconSize(QtCore.QSize(32, 32))
        self.add_covariate_btn.setObjectName("add_covariate_btn")
        self.gridLayout_3.addWidget(self.add_covariate_btn, 1, 0, 1, 1)
        self.remove_covariate_btn = QtGui.QPushButton(self.tab_3)
        self.remove_covariate_btn.setEnabled(False)
        self.remove_covariate_btn.setMinimumSize(QtCore.QSize(32, 32))
        self.remove_covariate_btn.setMaximumSize(QtCore.QSize(32, 32))
        self.remove_covariate_btn.setText("")
        self.remove_covariate_btn.setIcon(icon1)
        self.remove_covariate_btn.setIconSize(QtCore.QSize(32, 32))
        self.remove_covariate_btn.setObjectName("remove_covariate_btn")
        self.gridLayout_3.addWidget(self.remove_covariate_btn, 1, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_3)
        self.edit_tab.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.edit_tab)
        self.buttonBox = QtGui.QDialogButtonBox(edit_dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(edit_dialog)
        self.edit_tab.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), edit_dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), edit_dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(edit_dialog)

    def retranslateUi(self, edit_dialog):
        edit_dialog.setWindowTitle(QtGui.QApplication.translate("edit_dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("edit_dialog", "outcomes", None, QtGui.QApplication.UnicodeUTF8))
        self.grpbox_follow_ups.setTitle(QtGui.QApplication.translate("edit_dialog", "follow ups", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("edit_dialog", "tx groups", None, QtGui.QApplication.UnicodeUTF8))
        self.edit_tab.setTabText(self.edit_tab.indexOf(self.tab), QtGui.QApplication.translate("edit_dialog", "outcomes/follow-ups/groups", None, QtGui.QApplication.UnicodeUTF8))
        self.edit_tab.setTabText(self.edit_tab.indexOf(self.tab_2), QtGui.QApplication.translate("edit_dialog", "studies", None, QtGui.QApplication.UnicodeUTF8))
        self.edit_tab.setTabText(self.edit_tab.indexOf(self.tab_3), QtGui.QApplication.translate("edit_dialog", "covariates", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
