# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_dialog.ui'
#
# Created: Fri Jun 25 14:15:33 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_edit_dialog(object):
    def setupUi(self, edit_dialog):
        edit_dialog.setObjectName("edit_dialog")
        edit_dialog.resize(511, 335)
        edit_dialog.setMinimumSize(QtCore.QSize(511, 335))
        edit_dialog.setMaximumSize(QtCore.QSize(511, 335))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        edit_dialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/meta.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        edit_dialog.setWindowIcon(icon)
        self.buttonBox = QtGui.QDialogButtonBox(edit_dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 290, 461, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox = QtGui.QGroupBox(edit_dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 151, 271))
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.group_list = QtGui.QListView(self.groupBox)
        self.group_list.setGeometry(QtCore.QRect(0, 20, 151, 211))
        self.group_list.setAlternatingRowColors(True)
        self.group_list.setObjectName("group_list")
        self.add_group_btn = QtGui.QToolButton(self.groupBox)
        self.add_group_btn.setGeometry(QtCore.QRect(40, 230, 31, 31))
        self.add_group_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/function_icon_set/add_48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_group_btn.setIcon(icon1)
        self.add_group_btn.setIconSize(QtCore.QSize(64, 64))
        self.add_group_btn.setAutoRaise(True)
        self.add_group_btn.setObjectName("add_group_btn")
        self.add_group_btn_2 = QtGui.QToolButton(self.groupBox)
        self.add_group_btn_2.setGeometry(QtCore.QRect(70, 230, 31, 31))
        self.add_group_btn_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/function_icon_set/cancel_48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_group_btn_2.setIcon(icon2)
        self.add_group_btn_2.setIconSize(QtCore.QSize(64, 64))
        self.add_group_btn_2.setAutoRaise(True)
        self.add_group_btn_2.setObjectName("add_group_btn_2")
        self.groupBox_2 = QtGui.QGroupBox(edit_dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(170, 10, 161, 271))
        self.groupBox_2.setObjectName("groupBox_2")
        self.add_outcome_btn = QtGui.QToolButton(self.groupBox_2)
        self.add_outcome_btn.setGeometry(QtCore.QRect(50, 230, 31, 31))
        self.add_outcome_btn.setText("")
        self.add_outcome_btn.setIcon(icon1)
        self.add_outcome_btn.setIconSize(QtCore.QSize(64, 64))
        self.add_outcome_btn.setAutoRaise(True)
        self.add_outcome_btn.setObjectName("add_outcome_btn")
        self.outcome_list = QtGui.QListView(self.groupBox_2)
        self.outcome_list.setGeometry(QtCore.QRect(0, 20, 161, 209))
        self.outcome_list.setAlternatingRowColors(True)
        self.outcome_list.setObjectName("outcome_list")
        self.remove_outcome_btn = QtGui.QToolButton(self.groupBox_2)
        self.remove_outcome_btn.setGeometry(QtCore.QRect(80, 230, 31, 31))
        self.remove_outcome_btn.setText("")
        self.remove_outcome_btn.setIcon(icon2)
        self.remove_outcome_btn.setIconSize(QtCore.QSize(64, 64))
        self.remove_outcome_btn.setAutoRaise(True)
        self.remove_outcome_btn.setObjectName("remove_outcome_btn")
        self.grpbox_follow_ups = QtGui.QGroupBox(edit_dialog)
        self.grpbox_follow_ups.setGeometry(QtCore.QRect(340, 10, 161, 271))
        self.grpbox_follow_ups.setObjectName("grpbox_follow_ups")
        self.follow_up_list = QtGui.QListView(self.grpbox_follow_ups)
        self.follow_up_list.setGeometry(QtCore.QRect(0, 20, 161, 209))
        self.follow_up_list.setAlternatingRowColors(True)
        self.follow_up_list.setObjectName("follow_up_list")
        self.add_outcome_btn_2 = QtGui.QToolButton(self.grpbox_follow_ups)
        self.add_outcome_btn_2.setGeometry(QtCore.QRect(50, 230, 31, 31))
        self.add_outcome_btn_2.setText("")
        self.add_outcome_btn_2.setIcon(icon1)
        self.add_outcome_btn_2.setIconSize(QtCore.QSize(64, 64))
        self.add_outcome_btn_2.setAutoRaise(True)
        self.add_outcome_btn_2.setObjectName("add_outcome_btn_2")
        self.remove_outcome_btn_2 = QtGui.QToolButton(self.grpbox_follow_ups)
        self.remove_outcome_btn_2.setGeometry(QtCore.QRect(80, 230, 31, 31))
        self.remove_outcome_btn_2.setText("")
        self.remove_outcome_btn_2.setIcon(icon2)
        self.remove_outcome_btn_2.setIconSize(QtCore.QSize(64, 64))
        self.remove_outcome_btn_2.setAutoRaise(True)
        self.remove_outcome_btn_2.setObjectName("remove_outcome_btn_2")

        self.retranslateUi(edit_dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), edit_dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), edit_dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(edit_dialog)

    def retranslateUi(self, edit_dialog):
        edit_dialog.setWindowTitle(QtGui.QApplication.translate("edit_dialog", "Edit Dataset", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("edit_dialog", "tx groups", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("edit_dialog", "outcomes", None, QtGui.QApplication.UnicodeUTF8))
        self.grpbox_follow_ups.setTitle(QtGui.QApplication.translate("edit_dialog", "follow ups", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
