# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_dialog.ui'
#
# Created: Wed Feb 10 09:52:52 2010
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_edit_dialog(object):
    def setupUi(self, edit_dialog):
        edit_dialog.setObjectName("edit_dialog")
        edit_dialog.resize(688, 355)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        edit_dialog.setFont(font)
        self.horizontalLayout = QtGui.QHBoxLayout(edit_dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.editTabWidget = QtGui.QTabWidget(edit_dialog)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.editTabWidget.setFont(font)
        self.editTabWidget.setObjectName("editTabWidget")
        self.arms_tab = QtGui.QWidget()
        self.arms_tab.setObjectName("arms_tab")
        self.groupBox = QtGui.QGroupBox(self.arms_tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 151, 271))
        self.groupBox.setObjectName("groupBox")
        self.group_list = QtGui.QListView(self.groupBox)
        self.group_list.setGeometry(QtCore.QRect(0, 20, 151, 211))
        self.group_list.setAlternatingRowColors(True)
        self.group_list.setObjectName("group_list")
        self.nav_add_btn = QtGui.QToolButton(self.groupBox)
        self.nav_add_btn.setGeometry(QtCore.QRect(50, 230, 51, 41))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/function_icon_set/add_48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nav_add_btn.setIcon(icon)
        self.nav_add_btn.setIconSize(QtCore.QSize(64, 64))
        self.nav_add_btn.setAutoRaise(True)
        self.nav_add_btn.setObjectName("nav_add_btn")
        self.groupBox_2 = QtGui.QGroupBox(self.arms_tab)
        self.groupBox_2.setGeometry(QtCore.QRect(170, 20, 161, 271))
        self.groupBox_2.setObjectName("groupBox_2")
        self.nav_add_btn_2 = QtGui.QToolButton(self.groupBox_2)
        self.nav_add_btn_2.setGeometry(QtCore.QRect(50, 230, 51, 41))
        self.nav_add_btn_2.setIcon(icon)
        self.nav_add_btn_2.setIconSize(QtCore.QSize(64, 64))
        self.nav_add_btn_2.setAutoRaise(True)
        self.nav_add_btn_2.setObjectName("nav_add_btn_2")
        self.outcome_list = QtGui.QListView(self.groupBox_2)
        self.outcome_list.setGeometry(QtCore.QRect(10, 20, 141, 209))
        self.outcome_list.setAlternatingRowColors(True)
        self.outcome_list.setObjectName("outcome_list")
        self.editTabWidget.addTab(self.arms_tab, "")
        self.network_tab = QtGui.QWidget()
        self.network_tab.setObjectName("network_tab")
        self.widget = QtGui.QWidget(self.network_tab)
        self.widget.setGeometry(QtCore.QRect(0, 0, 661, 301))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.network_viewer = QtGui.QGraphicsView(self.widget)
        self.network_viewer.setObjectName("network_viewer")
        self.horizontalLayout_2.addWidget(self.network_viewer)
        self.frame_2 = QtGui.QFrame(self.widget)
        self.frame_2.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.widget1 = QtGui.QWidget(self.frame_2)
        self.widget1.setGeometry(QtCore.QRect(10, 45, 181, 91))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtGui.QVBoxLayout(self.widget1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtGui.QLabel(self.widget1)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.comboBox = QtGui.QComboBox(self.widget1)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout.addWidget(self.comboBox)
        self.label_4 = QtGui.QLabel(self.widget1)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.comboBox_2 = QtGui.QComboBox(self.widget1)
        self.comboBox_2.setObjectName("comboBox_2")
        self.verticalLayout.addWidget(self.comboBox_2)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.editTabWidget.addTab(self.network_tab, "")
        self.horizontalLayout.addWidget(self.editTabWidget)

        self.retranslateUi(edit_dialog)
        self.editTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(edit_dialog)

    def retranslateUi(self, edit_dialog):
        edit_dialog.setWindowTitle(QtGui.QApplication.translate("edit_dialog", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("edit_dialog", "tx groups", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("edit_dialog", "outcomes", None, QtGui.QApplication.UnicodeUTF8))
        self.editTabWidget.setTabText(self.editTabWidget.indexOf(self.arms_tab), QtGui.QApplication.translate("edit_dialog", "tx groups (arms)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("edit_dialog", "outcome:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("edit_dialog", "follow-up:", None, QtGui.QApplication.UnicodeUTF8))
        self.editTabWidget.setTabText(self.editTabWidget.indexOf(self.network_tab), QtGui.QApplication.translate("edit_dialog", "network", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
