# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_forest_plot.ui'
#
# Created: Fri Apr 12 14:30:03 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_edit_forest_plot_dlg(object):
    def setupUi(self, edit_forest_plot_dlg):
        edit_forest_plot_dlg.setObjectName(_fromUtf8("edit_forest_plot_dlg"))
        edit_forest_plot_dlg.resize(506, 434)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/meta.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        edit_forest_plot_dlg.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(edit_forest_plot_dlg)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(edit_forest_plot_dlg)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.col1_str_edit = QtGui.QLineEdit(self.groupBox)
        self.col1_str_edit.setObjectName(_fromUtf8("col1_str_edit"))
        self.gridLayout_2.addWidget(self.col1_str_edit, 0, 1, 1, 1)
        self.show_1 = QtGui.QCheckBox(self.groupBox)
        self.show_1.setChecked(True)
        self.show_1.setObjectName(_fromUtf8("show_1"))
        self.gridLayout_2.addWidget(self.show_1, 0, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.col2_str_edit = QtGui.QLineEdit(self.groupBox)
        self.col2_str_edit.setObjectName(_fromUtf8("col2_str_edit"))
        self.gridLayout_2.addWidget(self.col2_str_edit, 1, 1, 1, 1)
        self.show_2 = QtGui.QCheckBox(self.groupBox)
        self.show_2.setChecked(True)
        self.show_2.setObjectName(_fromUtf8("show_2"))
        self.gridLayout_2.addWidget(self.show_2, 1, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.col3_str_edit = QtGui.QLineEdit(self.groupBox)
        self.col3_str_edit.setObjectName(_fromUtf8("col3_str_edit"))
        self.gridLayout_2.addWidget(self.col3_str_edit, 2, 1, 1, 1)
        self.show_3 = QtGui.QCheckBox(self.groupBox)
        self.show_3.setChecked(True)
        self.show_3.setObjectName(_fromUtf8("show_3"))
        self.gridLayout_2.addWidget(self.show_3, 2, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 3, 0, 1, 1)
        self.col4_str_edit = QtGui.QLineEdit(self.groupBox)
        self.col4_str_edit.setObjectName(_fromUtf8("col4_str_edit"))
        self.gridLayout_2.addWidget(self.col4_str_edit, 3, 1, 1, 1)
        self.show_4 = QtGui.QCheckBox(self.groupBox)
        self.show_4.setChecked(True)
        self.show_4.setObjectName(_fromUtf8("show_4"))
        self.gridLayout_2.addWidget(self.show_4, 3, 2, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)
        self.verticalLayout.addWidget(self.groupBox)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_12 = QtGui.QLabel(edit_forest_plot_dlg)
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_4.addWidget(self.label_12, 0, 0, 1, 1)
        self.label_13 = QtGui.QLabel(edit_forest_plot_dlg)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_4.addWidget(self.label_13, 4, 0, 1, 1)
        self.x_ticks_le = QtGui.QLineEdit(edit_forest_plot_dlg)
        self.x_ticks_le.setObjectName(_fromUtf8("x_ticks_le"))
        self.gridLayout_4.addWidget(self.x_ticks_le, 4, 2, 1, 1)
        self.label_14 = QtGui.QLabel(edit_forest_plot_dlg)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_4.addWidget(self.label_14, 1, 0, 1, 1)
        self.plot_lb_le = QtGui.QLineEdit(edit_forest_plot_dlg)
        self.plot_lb_le.setObjectName(_fromUtf8("plot_lb_le"))
        self.gridLayout_4.addWidget(self.plot_lb_le, 1, 2, 1, 1)
        self.label_15 = QtGui.QLabel(edit_forest_plot_dlg)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_4.addWidget(self.label_15, 2, 0, 1, 1)
        self.plot_ub_le = QtGui.QLineEdit(edit_forest_plot_dlg)
        self.plot_ub_le.setObjectName(_fromUtf8("plot_ub_le"))
        self.gridLayout_4.addWidget(self.plot_ub_le, 2, 2, 1, 1)
        self.label_16 = QtGui.QLabel(edit_forest_plot_dlg)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_4.addWidget(self.label_16, 5, 0, 1, 1)
        self.show_summary_line = QtGui.QCheckBox(edit_forest_plot_dlg)
        self.show_summary_line.setText(_fromUtf8(""))
        self.show_summary_line.setChecked(True)
        self.show_summary_line.setObjectName(_fromUtf8("show_summary_line"))
        self.gridLayout_4.addWidget(self.show_summary_line, 5, 2, 1, 1)
        self.x_lbl_le = QtGui.QLineEdit(edit_forest_plot_dlg)
        self.x_lbl_le.setObjectName(_fromUtf8("x_lbl_le"))
        self.gridLayout_4.addWidget(self.x_lbl_le, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_3 = QtGui.QLabel(edit_forest_plot_dlg)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        self.image_path = QtGui.QLineEdit(edit_forest_plot_dlg)
        self.image_path.setObjectName(_fromUtf8("image_path"))
        self.horizontalLayout_4.addWidget(self.image_path)
        self.save_btn = QtGui.QPushButton(edit_forest_plot_dlg)
        self.save_btn.setMaximumSize(QtCore.QSize(25, 16777215))
        self.save_btn.setObjectName(_fromUtf8("save_btn"))
        self.horizontalLayout_4.addWidget(self.save_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.buttonBox = QtGui.QDialogButtonBox(edit_forest_plot_dlg)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(edit_forest_plot_dlg)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), edit_forest_plot_dlg.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), edit_forest_plot_dlg.reject)
        QtCore.QMetaObject.connectSlotsByName(edit_forest_plot_dlg)

    def retranslateUi(self, edit_forest_plot_dlg):
        edit_forest_plot_dlg.setWindowTitle(_translate("edit_forest_plot_dlg", "edit forest plot", None))
        self.groupBox.setTitle(_translate("edit_forest_plot_dlg", "column labels", None))
        self.label_2.setText(_translate("edit_forest_plot_dlg", "col 1 label:", None))
        self.col1_str_edit.setText(_translate("edit_forest_plot_dlg", "Studies", None))
        self.show_1.setText(_translate("edit_forest_plot_dlg", "show", None))
        self.label_4.setText(_translate("edit_forest_plot_dlg", "col 2 label:", None))
        self.col2_str_edit.setText(_translate("edit_forest_plot_dlg", "Estimate (Conf. Int.)", None))
        self.show_2.setText(_translate("edit_forest_plot_dlg", "show", None))
        self.label_5.setText(_translate("edit_forest_plot_dlg", "col 3 label:", None))
        self.col3_str_edit.setText(_translate("edit_forest_plot_dlg", "Ev/Trt", None))
        self.show_3.setText(_translate("edit_forest_plot_dlg", "show", None))
        self.label_6.setText(_translate("edit_forest_plot_dlg", "col 4 label:", None))
        self.col4_str_edit.setText(_translate("edit_forest_plot_dlg", "Ev/Ctrl", None))
        self.show_4.setText(_translate("edit_forest_plot_dlg", "show", None))
        self.label_12.setText(_translate("edit_forest_plot_dlg", "x label:", None))
        self.label_13.setText(_translate("edit_forest_plot_dlg", "x ticks:", None))
        self.x_ticks_le.setText(_translate("edit_forest_plot_dlg", "[default]", None))
        self.label_14.setText(_translate("edit_forest_plot_dlg", "x-axis lower bound", None))
        self.plot_lb_le.setText(_translate("edit_forest_plot_dlg", "[default]", None))
        self.label_15.setText(_translate("edit_forest_plot_dlg", "x-axis upper bound", None))
        self.plot_ub_le.setText(_translate("edit_forest_plot_dlg", "[default]", None))
        self.label_16.setText(_translate("edit_forest_plot_dlg", "show summary line:", None))
        self.x_lbl_le.setText(_translate("edit_forest_plot_dlg", "[default]", None))
        self.label_3.setText(_translate("edit_forest_plot_dlg", "save image to:", None))
        self.image_path.setText(_translate("edit_forest_plot_dlg", "./r_tmp/forest.png", None))
        self.save_btn.setText(_translate("edit_forest_plot_dlg", "...", None))

import icons_rc
