# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'meta.ui'
#
# Created: Mon Apr 29 14:16:33 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import ma_data_table_view

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1000, 618)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/misc/meta.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.centralwidget.setFont(font)
        self.centralwidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setContentsMargins(2, -1, 2, 0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.nav_frame = QtGui.QFrame(self.centralwidget)
        self.nav_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.nav_frame.setFrameShadow(QtGui.QFrame.Plain)
        self.nav_frame.setObjectName(_fromUtf8("nav_frame"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.nav_frame)
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setContentsMargins(0, 1, 0, 0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        #self.tableView = QtGui.QTableView(self.nav_frame)
        self.tableView = ma_data_table_view.MADataTable(self.nav_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView.sizePolicy().hasHeightForWidth())
        self.tableView.setSizePolicy(sizePolicy)
        self.tableView.setAlternatingRowColors(True)
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.verticalLayout.addWidget(self.tableView)
        self.frame = QtGui.QFrame(self.nav_frame)
        self.frame.setMinimumSize(QtCore.QSize(0, 65))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.controlbutton_layot = QtGui.QHBoxLayout()
        self.controlbutton_layot.setSpacing(0)
        self.controlbutton_layot.setObjectName(_fromUtf8("controlbutton_layot"))
        self.frame_2 = QtGui.QFrame(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(181, 61))
        self.frame_2.setMaximumSize(QtCore.QSize(181, 61))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.nav_left_btn = QtGui.QToolButton(self.frame_2)
        self.nav_left_btn.setGeometry(QtCore.QRect(0, 10, 20, 41))
        self.nav_left_btn.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/misc/left_arrow.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nav_left_btn.setIcon(icon1)
        self.nav_left_btn.setIconSize(QtCore.QSize(64, 64))
        self.nav_left_btn.setAutoRaise(True)
        self.nav_left_btn.setObjectName(_fromUtf8("nav_left_btn"))
        self.nav_up_btn = QtGui.QToolButton(self.frame_2)
        self.nav_up_btn.setGeometry(QtCore.QRect(40, 0, 51, 20))
        self.nav_up_btn.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/misc/up_arrow.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nav_up_btn.setIcon(icon2)
        self.nav_up_btn.setIconSize(QtCore.QSize(64, 64))
        self.nav_up_btn.setAutoRaise(True)
        self.nav_up_btn.setObjectName(_fromUtf8("nav_up_btn"))
        self.nav_down_btn = QtGui.QToolButton(self.frame_2)
        self.nav_down_btn.setGeometry(QtCore.QRect(40, 40, 51, 20))
        self.nav_down_btn.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/misc/down_arrow.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nav_down_btn.setIcon(icon3)
        self.nav_down_btn.setIconSize(QtCore.QSize(64, 64))
        self.nav_down_btn.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.nav_down_btn.setAutoRaise(True)
        self.nav_down_btn.setArrowType(QtCore.Qt.NoArrow)
        self.nav_down_btn.setObjectName(_fromUtf8("nav_down_btn"))
        self.nav_lbl = QtGui.QLabel(self.frame_2)
        self.nav_lbl.setGeometry(QtCore.QRect(20, 20, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.nav_lbl.setFont(font)
        self.nav_lbl.setText(_fromUtf8(""))
        self.nav_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.nav_lbl.setObjectName(_fromUtf8("nav_lbl"))
        self.nav_right_btn = QtGui.QToolButton(self.frame_2)
        self.nav_right_btn.setGeometry(QtCore.QRect(110, 10, 20, 41))
        self.nav_right_btn.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/misc/right_arrow.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nav_right_btn.setIcon(icon4)
        self.nav_right_btn.setIconSize(QtCore.QSize(64, 64))
        self.nav_right_btn.setAutoRaise(True)
        self.nav_right_btn.setObjectName(_fromUtf8("nav_right_btn"))
        self.nav_add_btn = QtGui.QToolButton(self.frame_2)
        self.nav_add_btn.setGeometry(QtCore.QRect(130, 10, 51, 41))
        self.nav_add_btn.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/function_icon_set/function_icon_set/add_48.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nav_add_btn.setIcon(icon5)
        self.nav_add_btn.setIconSize(QtCore.QSize(64, 64))
        self.nav_add_btn.setAutoRaise(True)
        self.nav_add_btn.setObjectName(_fromUtf8("nav_add_btn"))
        self.controlbutton_layot.addWidget(self.frame_2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(80, 25))
        self.label.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(80, 25))
        self.label_3.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.cur_time_lbl = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cur_time_lbl.sizePolicy().hasHeightForWidth())
        self.cur_time_lbl.setSizePolicy(sizePolicy)
        self.cur_time_lbl.setMinimumSize(QtCore.QSize(80, 25))
        self.cur_time_lbl.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cur_time_lbl.setFont(font)
        self.cur_time_lbl.setText(_fromUtf8(""))
        self.cur_time_lbl.setObjectName(_fromUtf8("cur_time_lbl"))
        self.gridLayout.addWidget(self.cur_time_lbl, 1, 1, 1, 1)
        self.cur_outcome_lbl = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cur_outcome_lbl.sizePolicy().hasHeightForWidth())
        self.cur_outcome_lbl.setSizePolicy(sizePolicy)
        self.cur_outcome_lbl.setMinimumSize(QtCore.QSize(80, 25))
        self.cur_outcome_lbl.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cur_outcome_lbl.setFont(font)
        self.cur_outcome_lbl.setText(_fromUtf8(""))
        self.cur_outcome_lbl.setObjectName(_fromUtf8("cur_outcome_lbl"))
        self.gridLayout.addWidget(self.cur_outcome_lbl, 0, 1, 1, 1)
        self.controlbutton_layot.addLayout(self.gridLayout)
        self.horizontalLayout.addLayout(self.controlbutton_layot)
        spacerItem = QtGui.QSpacerItem(396, 18, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.ci_layot = QtGui.QHBoxLayout()
        self.ci_layot.setObjectName(_fromUtf8("ci_layot"))
        self.horizontalLayout.addLayout(self.ci_layot)
        self.verticalLayout.addWidget(self.frame)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addWidget(self.nav_frame)
        self.dataset_file_lbl = QtGui.QLabel(self.centralwidget)
        self.dataset_file_lbl.setText(_fromUtf8(""))
        self.dataset_file_lbl.setObjectName(_fromUtf8("dataset_file_lbl"))
        self.verticalLayout_3.addWidget(self.dataset_file_lbl)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menu_bar = QtGui.QMenuBar(MainWindow)
        self.menu_bar.setGeometry(QtCore.QRect(0, 0, 1000, 22))
        self.menu_bar.setObjectName(_fromUtf8("menu_bar"))
        self.menu_file = QtGui.QMenu(self.menu_bar)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.menu_file.setFont(font)
        self.menu_file.setObjectName(_fromUtf8("menu_file"))
        self.action_open_recent_2 = QtGui.QMenu(self.menu_file)
        self.action_open_recent_2.setObjectName(_fromUtf8("action_open_recent_2"))
        self.menuAnalysis = QtGui.QMenu(self.menu_bar)
        self.menuAnalysis.setObjectName(_fromUtf8("menuAnalysis"))
        self.menuMetric = QtGui.QMenu(self.menuAnalysis)
        self.menuMetric.setObjectName(_fromUtf8("menuMetric"))
        self.menuDataset = QtGui.QMenu(self.menu_bar)
        self.menuDataset.setObjectName(_fromUtf8("menuDataset"))
        self.menuEdit = QtGui.QMenu(self.menu_bar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuHelp = QtGui.QMenu(self.menu_bar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menu_bar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action_save = QtGui.QAction(MainWindow)
        self.action_save.setObjectName(_fromUtf8("action_save"))
        self.action_open = QtGui.QAction(MainWindow)
        self.action_open.setObjectName(_fromUtf8("action_open"))
        self.action_quit = QtGui.QAction(MainWindow)
        self.action_quit.setObjectName(_fromUtf8("action_quit"))
        self.action_go = QtGui.QAction(MainWindow)
        self.action_go.setObjectName(_fromUtf8("action_go"))
        self.action_edit = QtGui.QAction(MainWindow)
        self.action_edit.setObjectName(_fromUtf8("action_edit"))
        self.action_view_network = QtGui.QAction(MainWindow)
        self.action_view_network.setObjectName(_fromUtf8("action_view_network"))
        self.action_add_covariate = QtGui.QAction(MainWindow)
        self.action_add_covariate.setObjectName(_fromUtf8("action_add_covariate"))
        self.action_cum_ma = QtGui.QAction(MainWindow)
        self.action_cum_ma.setObjectName(_fromUtf8("action_cum_ma"))
        self.action_loo_ma = QtGui.QAction(MainWindow)
        self.action_loo_ma.setObjectName(_fromUtf8("action_loo_ma"))
        self.actionOR = QtGui.QAction(MainWindow)
        self.actionOR.setObjectName(_fromUtf8("actionOR"))
        self.actionRR = QtGui.QAction(MainWindow)
        self.actionRR.setObjectName(_fromUtf8("actionRR"))
        self.actionTX_Mean_one_arm = QtGui.QAction(MainWindow)
        self.actionTX_Mean_one_arm.setObjectName(_fromUtf8("actionTX_Mean_one_arm"))
        self.actionYo = QtGui.QAction(MainWindow)
        self.actionYo.setObjectName(_fromUtf8("actionYo"))
        self.actionNew_dataset = QtGui.QAction(MainWindow)
        self.actionNew_dataset.setObjectName(_fromUtf8("actionNew_dataset"))
        self.action_new_dataset = QtGui.QAction(MainWindow)
        self.action_new_dataset.setObjectName(_fromUtf8("action_new_dataset"))
        self.action_meta_regression = QtGui.QAction(MainWindow)
        self.action_meta_regression.setObjectName(_fromUtf8("action_meta_regression"))
        self.action_undo = QtGui.QAction(MainWindow)
        self.action_undo.setObjectName(_fromUtf8("action_undo"))
        self.action_redo = QtGui.QAction(MainWindow)
        self.action_redo.setObjectName(_fromUtf8("action_redo"))
        self.action_copy = QtGui.QAction(MainWindow)
        self.action_copy.setObjectName(_fromUtf8("action_copy"))
        self.action_paste = QtGui.QAction(MainWindow)
        self.action_paste.setObjectName(_fromUtf8("action_paste"))
        self.action_subgroup_ma = QtGui.QAction(MainWindow)
        self.action_subgroup_ma.setObjectName(_fromUtf8("action_subgroup_ma"))
        self.action_save_as = QtGui.QAction(MainWindow)
        self.action_save_as.setObjectName(_fromUtf8("action_save_as"))
        self.actionDfsf = QtGui.QAction(MainWindow)
        self.actionDfsf.setObjectName(_fromUtf8("actionDfsf"))
        self.action_open_help = QtGui.QAction(MainWindow)
        self.action_open_help.setObjectName(_fromUtf8("action_open_help"))
        self.action_change_conf_level = QtGui.QAction(MainWindow)
        self.action_change_conf_level.setObjectName(_fromUtf8("action_change_conf_level"))
        self.action_open_recent_2.addAction(self.actionDfsf)
        self.menu_file.addAction(self.action_save)
        self.menu_file.addAction(self.action_save_as)
        self.menu_file.addAction(self.action_open)
        self.menu_file.addAction(self.action_open_recent_2.menuAction())
        self.menu_file.addAction(self.action_quit)
        self.menuAnalysis.addAction(self.menuMetric.menuAction())
        self.menuAnalysis.addSeparator()
        self.menuAnalysis.addAction(self.action_go)
        self.menuAnalysis.addSeparator()
        self.menuAnalysis.addAction(self.action_cum_ma)
        self.menuAnalysis.addAction(self.action_loo_ma)
        self.menuAnalysis.addAction(self.action_subgroup_ma)
        self.menuAnalysis.addSeparator()
        self.menuAnalysis.addAction(self.action_meta_regression)
        self.menuAnalysis.addAction(self.action_change_conf_level)
        self.menuDataset.addAction(self.action_new_dataset)
        self.menuDataset.addSeparator()
        self.menuDataset.addAction(self.action_edit)
        self.menuDataset.addAction(self.action_view_network)
        self.menuDataset.addAction(self.action_add_covariate)
        self.menuEdit.addAction(self.action_undo)
        self.menuEdit.addAction(self.action_redo)
        self.menuEdit.addAction(self.action_copy)
        self.menuEdit.addAction(self.action_paste)
        self.menuHelp.addAction(self.action_open_help)
        self.menu_bar.addAction(self.menu_file.menuAction())
        self.menu_bar.addAction(self.menuEdit.menuAction())
        self.menu_bar.addAction(self.menuAnalysis.menuAction())
        self.menu_bar.addAction(self.menuDataset.menuAction())
        self.menu_bar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "OpenMeta[analyst]", None))
        self.label.setText(_translate("MainWindow", "outcome:", None))
        self.label_3.setText(_translate("MainWindow", "follow-up:", None))
        self.menu_file.setTitle(_translate("MainWindow", "File", None))
        self.action_open_recent_2.setTitle(_translate("MainWindow", "open recent...", None))
        self.menuAnalysis.setTitle(_translate("MainWindow", "Analysis", None))
        self.menuMetric.setTitle(_translate("MainWindow", "metric", None))
        self.menuDataset.setTitle(_translate("MainWindow", "Dataset", None))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.action_save.setText(_translate("MainWindow", "save", None))
        self.action_open.setText(_translate("MainWindow", "open...", None))
        self.action_quit.setText(_translate("MainWindow", "quit", None))
        self.action_go.setText(_translate("MainWindow", "meta-analysis...", None))
        self.action_edit.setText(_translate("MainWindow", "edit...", None))
        self.action_view_network.setText(_translate("MainWindow", "view network...", None))
        self.action_add_covariate.setText(_translate("MainWindow", "add covariate...", None))
        self.action_cum_ma.setText(_translate("MainWindow", "cumulative meta-analysis...", None))
        self.action_loo_ma.setText(_translate("MainWindow", "leave-one-out meta-analysis...", None))
        self.actionOR.setText(_translate("MainWindow", "OR", None))
        self.actionRR.setText(_translate("MainWindow", "RR", None))
        self.actionTX_Mean_one_arm.setText(_translate("MainWindow", "TX Mean (one-arm)", None))
        self.actionYo.setText(_translate("MainWindow", "yo", None))
        self.actionNew_dataset.setText(_translate("MainWindow", "new dataset...", None))
        self.action_new_dataset.setText(_translate("MainWindow", "new dataset...", None))
        self.action_meta_regression.setText(_translate("MainWindow", "meta-regression", None))
        self.action_undo.setText(_translate("MainWindow", "undo (ctrl + z)", None))
        self.action_redo.setText(_translate("MainWindow", "redo (ctrl + y)", None))
        self.action_copy.setText(_translate("MainWindow", "copy (ctrl + c)", None))
        self.action_paste.setText(_translate("MainWindow", "paste (ctrl + v)", None))
        self.action_subgroup_ma.setText(_translate("MainWindow", "subgroup meta-analysis", None))
        self.action_save_as.setText(_translate("MainWindow", "save as...", None))
        self.actionDfsf.setText(_translate("MainWindow", "(none)", None))
        self.action_open_help.setText(_translate("MainWindow", "open help", None))
        self.action_change_conf_level.setText(_translate("MainWindow", "change confidence level", None))

import icons_rc
