# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ma_specs2.ui'
#
# Created: Fri Nov 05 15:48:39 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(551, 573)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        Dialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/meta.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(self.tab)
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.method_cbo_box = QtGui.QComboBox(self.tab)
        self.method_cbo_box.setObjectName("method_cbo_box")
        self.gridLayout.addWidget(self.method_cbo_box, 0, 1, 1, 1)
        self.parameter_grp_box = QtGui.QGroupBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.parameter_grp_box.sizePolicy().hasHeightForWidth())
        self.parameter_grp_box.setSizePolicy(sizePolicy)
        self.parameter_grp_box.setMinimumSize(QtCore.QSize(0, 200))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.parameter_grp_box.setFont(font)
        self.parameter_grp_box.setTitle("")
        self.parameter_grp_box.setObjectName("parameter_grp_box")
        self.gridLayout.addWidget(self.parameter_grp_box, 1, 0, 1, 2)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.effect_str_edit_2 = QtGui.QLineEdit(self.tab_2)
        self.effect_str_edit_2.setGeometry(QtCore.QRect(120, 460, 113, 20))
        self.effect_str_edit_2.setObjectName("effect_str_edit_2")
        self.label_3 = QtGui.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(20, 460, 101, 31))
        self.label_3.setObjectName("label_3")
        self.groupBox = QtGui.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 511, 201))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.col1_str_edit = QtGui.QLineEdit(self.groupBox)
        self.col1_str_edit.setObjectName("col1_str_edit")
        self.gridLayout_2.addWidget(self.col1_str_edit, 0, 1, 1, 1)
        self.show_1 = QtGui.QCheckBox(self.groupBox)
        self.show_1.setChecked(True)
        self.show_1.setObjectName("show_1")
        self.gridLayout_2.addWidget(self.show_1, 0, 2, 1, 1)
        self.align_1 = QtGui.QComboBox(self.groupBox)
        self.align_1.setModelColumn(0)
        self.align_1.setObjectName("align_1")
        self.align_1.addItem("")
        self.align_1.addItem("")
        self.gridLayout_2.addWidget(self.align_1, 0, 3, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.col2_str_edit = QtGui.QLineEdit(self.groupBox)
        self.col2_str_edit.setObjectName("col2_str_edit")
        self.gridLayout_2.addWidget(self.col2_str_edit, 1, 1, 1, 1)
        self.show_2 = QtGui.QCheckBox(self.groupBox)
        self.show_2.setChecked(True)
        self.show_2.setObjectName("show_2")
        self.gridLayout_2.addWidget(self.show_2, 1, 2, 1, 1)
        self.align_2 = QtGui.QComboBox(self.groupBox)
        self.align_2.setModelColumn(0)
        self.align_2.setObjectName("align_2")
        self.align_2.addItem("")
        self.align_2.addItem("")
        self.gridLayout_2.addWidget(self.align_2, 1, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.col3_str_edit = QtGui.QLineEdit(self.groupBox)
        self.col3_str_edit.setObjectName("col3_str_edit")
        self.gridLayout_2.addWidget(self.col3_str_edit, 2, 1, 1, 1)
        self.show_3 = QtGui.QCheckBox(self.groupBox)
        self.show_3.setChecked(True)
        self.show_3.setObjectName("show_3")
        self.gridLayout_2.addWidget(self.show_3, 2, 2, 1, 1)
        self.align_3 = QtGui.QComboBox(self.groupBox)
        self.align_3.setModelColumn(0)
        self.align_3.setObjectName("align_3")
        self.align_3.addItem("")
        self.align_3.addItem("")
        self.gridLayout_2.addWidget(self.align_3, 2, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 3, 0, 1, 1)
        self.col4_str_edit = QtGui.QLineEdit(self.groupBox)
        self.col4_str_edit.setObjectName("col4_str_edit")
        self.gridLayout_2.addWidget(self.col4_str_edit, 3, 1, 1, 1)
        self.show_4 = QtGui.QCheckBox(self.groupBox)
        self.show_4.setChecked(True)
        self.show_4.setObjectName("show_4")
        self.gridLayout_2.addWidget(self.show_4, 3, 2, 1, 1)
        self.align_4 = QtGui.QComboBox(self.groupBox)
        self.align_4.setModelColumn(0)
        self.align_4.setObjectName("align_4")
        self.align_4.addItem("")
        self.align_4.addItem("")
        self.gridLayout_2.addWidget(self.align_4, 3, 3, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)
        self.lineEdit = QtGui.QLineEdit(self.tab_2)
        self.lineEdit.setGeometry(QtCore.QRect(120, 410, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_7 = QtGui.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(20, 400, 101, 31))
        self.label_7.setObjectName("label_7")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Method & Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "analysis method:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Dialog", "method", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "save image to:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "column labels", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "col 1 label:", None, QtGui.QApplication.UnicodeUTF8))
        self.col1_str_edit.setText(QtGui.QApplication.translate("Dialog", "Studies", None, QtGui.QApplication.UnicodeUTF8))
        self.show_1.setText(QtGui.QApplication.translate("Dialog", "show", None, QtGui.QApplication.UnicodeUTF8))
        self.align_1.setItemText(0, QtGui.QApplication.translate("Dialog", "left", None, QtGui.QApplication.UnicodeUTF8))
        self.align_1.setItemText(1, QtGui.QApplication.translate("Dialog", "right", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "col 2 label:", None, QtGui.QApplication.UnicodeUTF8))
        self.col2_str_edit.setText(QtGui.QApplication.translate("Dialog", "ES (LL, UL)", None, QtGui.QApplication.UnicodeUTF8))
        self.show_2.setText(QtGui.QApplication.translate("Dialog", "show", None, QtGui.QApplication.UnicodeUTF8))
        self.align_2.setItemText(0, QtGui.QApplication.translate("Dialog", "left", None, QtGui.QApplication.UnicodeUTF8))
        self.align_2.setItemText(1, QtGui.QApplication.translate("Dialog", "right", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "col 3 label:", None, QtGui.QApplication.UnicodeUTF8))
        self.col3_str_edit.setText(QtGui.QApplication.translate("Dialog", "Ev/Trt", None, QtGui.QApplication.UnicodeUTF8))
        self.show_3.setText(QtGui.QApplication.translate("Dialog", "show", None, QtGui.QApplication.UnicodeUTF8))
        self.align_3.setItemText(0, QtGui.QApplication.translate("Dialog", "left", None, QtGui.QApplication.UnicodeUTF8))
        self.align_3.setItemText(1, QtGui.QApplication.translate("Dialog", "right", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "col 4 label:", None, QtGui.QApplication.UnicodeUTF8))
        self.col4_str_edit.setText(QtGui.QApplication.translate("Dialog", "Ev/Ctrl", None, QtGui.QApplication.UnicodeUTF8))
        self.show_4.setText(QtGui.QApplication.translate("Dialog", "show", None, QtGui.QApplication.UnicodeUTF8))
        self.align_4.setItemText(0, QtGui.QApplication.translate("Dialog", "left", None, QtGui.QApplication.UnicodeUTF8))
        self.align_4.setItemText(1, QtGui.QApplication.translate("Dialog", "right", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "x label:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Dialog", "forest plot", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
