# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'start_up.ui'
#
# Created: Tue Jan 25 16:37:55 2011
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_WelcomeDialog(object):
    def setupUi(self, WelcomeDialog):
        WelcomeDialog.setObjectName("WelcomeDialog")
        WelcomeDialog.resize(502, 197)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        WelcomeDialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/meta.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        WelcomeDialog.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(WelcomeDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtGui.QGroupBox(WelcomeDialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.dataset_name_le = QtGui.QLineEdit(self.groupBox)
        self.dataset_name_le.setObjectName("dataset_name_le")
        self.horizontalLayout_3.addWidget(self.dataset_name_le)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 2)
        self.bin_radio = QtGui.QRadioButton(self.groupBox)
        self.bin_radio.setChecked(True)
        self.bin_radio.setObjectName("bin_radio")
        self.buttonGroup = QtGui.QButtonGroup(WelcomeDialog)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.bin_radio)
        self.gridLayout.addWidget(self.bin_radio, 1, 0, 1, 1)
        self.diag_radio = QtGui.QRadioButton(self.groupBox)
        self.diag_radio.setObjectName("diag_radio")
        self.buttonGroup.addButton(self.diag_radio)
        self.gridLayout.addWidget(self.diag_radio, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 2, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.chk_show = QtGui.QCheckBox(WelcomeDialog)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.chk_show.setFont(font)
        self.chk_show.setChecked(True)
        self.chk_show.setObjectName("chk_show")
        self.horizontalLayout_2.addWidget(self.chk_show)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.open_btn = QtGui.QPushButton(WelcomeDialog)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/function_icon_set/folder_48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_btn.setIcon(icon1)
        self.open_btn.setObjectName("open_btn")
        self.horizontalLayout.addWidget(self.open_btn)
        self.open_recent_btn = QtGui.QPushButton(WelcomeDialog)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.open_recent_btn.setFont(font)
        self.open_recent_btn.setIcon(icon1)
        self.open_recent_btn.setObjectName("open_recent_btn")
        self.horizontalLayout.addWidget(self.open_recent_btn)
        self.create_new_btn = QtGui.QPushButton(WelcomeDialog)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/function_icon_set/add_48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.create_new_btn.setIcon(icon2)
        self.create_new_btn.setObjectName("create_new_btn")
        self.horizontalLayout.addWidget(self.create_new_btn)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(WelcomeDialog)
        QtCore.QMetaObject.connectSlotsByName(WelcomeDialog)

    def retranslateUi(self, WelcomeDialog):
        WelcomeDialog.setWindowTitle(QtGui.QApplication.translate("WelcomeDialog", "Welcome to OpenMeta", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("WelcomeDialog", "new dataset", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("WelcomeDialog", "name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("WelcomeDialog", "what sort of data will you be working with?", None, QtGui.QApplication.UnicodeUTF8))
        self.bin_radio.setText(QtGui.QApplication.translate("WelcomeDialog", "continuous and/or binary", None, QtGui.QApplication.UnicodeUTF8))
        self.diag_radio.setText(QtGui.QApplication.translate("WelcomeDialog", "diagnostic", None, QtGui.QApplication.UnicodeUTF8))
        self.chk_show.setText(QtGui.QApplication.translate("WelcomeDialog", "show this window on start-up", None, QtGui.QApplication.UnicodeUTF8))
        self.open_btn.setText(QtGui.QApplication.translate("WelcomeDialog", "open ...", None, QtGui.QApplication.UnicodeUTF8))
        self.open_recent_btn.setText(QtGui.QApplication.translate("WelcomeDialog", "open recent", None, QtGui.QApplication.UnicodeUTF8))
        self.create_new_btn.setText(QtGui.QApplication.translate("WelcomeDialog", "create new", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
import icons_rc
